### ISSUE TITLE
Mempool Summary Page times out

### ISSUE THREAD

**Issue by sangaman** [janoside/btc-rpc-explorer#127]
**Describe the bug**
Going to the mempool page fails with `ESOCKETTIMEDOUT` (once I saw a 504 Gateway error, although I haven't seen it since).

**Environment (please complete the following information):**
 - bitcoind 0.18.0
 - node 10.15.3
 - Firefox
 - Commit 256b4650c9b1283418a0652ac3f65e6a299b22a4

**To Reproduce**
Go to the mempool summary page.

**Screenshots or Log Output**
```
/home/bitcoin/btc-rpc-explorer/views/mempool-summary.pug:22
    20| 					tr
    21| 						td(class="properties-header") Transaction Count
  > 22| 						td #{getmempoolinfo.size.toLocaleString()}
    23| 
    24| 					tr
    25| 						- var mem1Data = utils.formatLargeNumber(getmempoolinfo.usage, 2);

Cannot read property 'size' of undefined

TypeError: /home/bitcoin/btc-rpc-explorer/views/mempool-summary.pug:22
    20| 					tr
    21| 						td(class="properties-header") Transaction Count
  > 22| 						td #{getmempoolinfo.size.toLocaleString()}
    23| 
    24| 					tr
    25| 						- var mem1Data = utils.formatLargeNumber(getmempoolinfo.usage, 2);

Cannot read property 'size' of undefined
    at eval (eval at wrap (/home/bitcoin/btc-rpc-explorer/node_modules/pug-runtime/wrap.js:6:10), <anonymous>:690:72)
    at template (eval at wrap (/home/bitcoin/btc-rpc-explorer/node_modules/pug-runtime/wrap.js:6:10), <anonymous>:2275:72)
    at Object.exports.renderFile (/home/bitcoin/btc-rpc-explorer/node_modules/pug/lib/index.js:427:38)
    at Object.exports.renderFile (/home/bitcoin/btc-rpc-explorer/node_modules/pug/lib/index.js:417:21)
    at exports.__express (/home/bitcoin/btc-rpc-explorer/node_modules/pug/lib/index.js:464:11)
    at View.app.engine (/home/bitcoin/btc-rpc-explorer/app.js:61:23)
    at View.render (/home/bitcoin/btc-rpc-explorer/node_modules/express/lib/view.js:135:8)
    at tryRender (/home/bitcoin/btc-rpc-explorer/node_modules/express/lib/application.js:640:10)
    at Function.render (/home/bitcoin/btc-rpc-explorer/node_modules/express/lib/application.js:592:3)
    at ServerResponse.render (/home/bitcoin/btc-rpc-explorer/node_modules/express/lib/response.js:1008:7)
    at /home/bitcoin/btc-rpc-explorer/routes/baseActionsRouter.js:175:7
```

**Comment by zooooooooo** [comment]
I also have experienced this on Mempool and Unconfirmed Tx Pages.

I tested on chaintools.io and same issue. Mempool page never loads, Unconfirmed Tx page loads with error:

![image](https://user-images.githubusercontent.com/33195081/57897273-0f27d280-7822-11e9-918f-f14f290de716.png)

`btcexp:error Error 38eh39hdee: Error: ESOCKETTIMEDOUT, json: {"cause":{"code":"ESOCKETTIMEDOUT","connect":false},"isOperational":true,"code":"ESOCKETTIMEDOUT","connect":false}, userData: [object Object] (json: {}) +5s
  btcexp:error Stack: Error: ESOCKETTIMEDOUT
  btcexp:error     at ClientRequest.<anonymous> (\node_modules\request\request.js:816:19)
  btcexp:error     at Object.onceWrapper (events.js:273:13)
  btcexp:error     at ClientRequest.emit (events.js:182:13)
  btcexp:error     at Socket.emitRequestTimeout (_http_client.js:668:40)
  btcexp:error     at Object.onceWrapper (events.js:273:13)
  btcexp:error     at Socket.emit (events.js:182:13)
  btcexp:error     at Socket._onTimeout (net.js:452:8)
  btcexp:error     at listOnTimeout (timers.js:324:15)
  btcexp:error     at processTimers (timers.js:268:5) +0ms
  btcexp:app Unhandled Rejection at: Promise Promise {
  <rejected> { Error: ESOCKETTIMEDOUT
      at ClientRequest.<anonymous> (\node_modules\request\request.js:816:19)
      at Object.onceWrapper (events.js:273:13)
      at ClientRequest.emit (events.js:182:13)
      at Socket.emitRequestTimeout (_http_client.js:668:40)
      at Object.onceWrapper (events.js:273:13)
      at Socket.emit (events.js:182:13)
      at Socket._onTimeout (net.js:452:8)
      at listOnTimeout (timers.js:324:15)
      at processTimers (timers.js:268:5)
    cause:
     { Error: ESOCKETTIMEDOUT
         at ClientRequest.<anonymous> \node_modules\request\request.js:816:19)
         at Object.onceWrapper (events.js:273:13)
         at ClientRequest.emit (events.js:182:13)
         at Socket.emitRequestTimeout (_http_client.js:668:40)
         at Object.onceWrapper (events.js:273:13)
         at Socket.emit (events.js:182:13)
         at Socket._onTimeout (net.js:452:8)
         at listOnTimeout (timers.js:324:15)
         at processTimers (timers.js:268:5) code: 'ESOCKETTIMEDOUT', connect: false },
    isOperational: true,
    code: 'ESOCKETTIMEDOUT',
    connect: false } } reason: { Error: ESOCKETTIMEDOUT
    at ClientRequest.<anonymous> (\node_modules\request\request.js:816:19)
    at Object.onceWrapper (events.js:273:13)
    at ClientRequest.emit (events.js:182:13)
    at Socket.emitRequestTimeout (_http_client.js:668:40)
    at Object.onceWrapper (events.js:273:13)
    at Socket.emit (events.js:182:13)
    at Socket._onTimeout (net.js:452:8)
    at listOnTimeout (timers.js:324:15)
    at processTimers (timers.js:268:5)
  cause:
   { Error: ESOCKETTIMEDOUT
       at ClientRequest.<anonymous> (\node_modules\request\request.js:816:19)
       at Object.onceWrapper (events.js:273:13)
       at ClientRequest.emit (events.js:182:13)
       at Socket.emitRequestTimeout (_http_client.js:668:40)
       at Object.onceWrapper (events.js:273:13)
       at Socket.emit (events.js:182:13)
       at Socket._onTimeout (net.js:452:8)
       at listOnTimeout (timers.js:324:15)
       at processTimers (timers.js:268:5) code: 'ESOCKETTIMEDOUT', connect: false },
  isOperational: true,
  code: 'ESOCKETTIMEDOUT',
  connect: false } stack: Error: ESOCKETTIMEDOUT
    at ClientRequest.<anonymous> (\node_modules\request\request.js:816:19)
    at Object.onceWrapper (events.js:273:13)
    at ClientRequest.emit (events.js:182:13)
    at Socket.emitRequestTimeout (_http_client.js:668:40)
    at Object.onceWrapper (events.js:273:13)
    at Socket.emit (events.js:182:13)
    at Socket._onTimeout (net.js:452:8)
    at listOnTimeout (timers.js:324:15)
    at processTimers (timers.js:268:5) +1ms
`

**Comment by zooooooooo** [comment]
Seems to be working now, on both my local node and Chaintools

Probably had something to do with Bitcoin Core

**Comment by sangaman** [comment]
It still does not work for me. The page hung for a minute or two and eventually gave me a 504 error gateway timeout. Other things like checking an address or transaction still work.

**Comment by zooooooooo** [comment]
Confirming that it is not working again on my end. I still think this has something to do with Bitcoin Core

**Comment by Relaxo143** [comment]
It happens when the mempool is too full. You need to increase the timeout time in the config of btc-rpc-explorer. I think the default is 5000ms. I changed it to 10 000 and it`s working now.

**Comment by sangaman** [comment]
Maybe the scope of these calls should be limited to prevent the page load from taking so long. `getmempoolinfo` returns almost immediately even with a decently sized mempool. For unconfirmed transaction for example it shouldn't try to load every unconfirmed transaction at once (if that's what it's doing).

**Comment by mercurytoxic** [comment]
Changed timeout to 10000 and then to 20000 and still showing the same timeout behavior on mempool and unconfirmed transactions pages. Current mempool is around 48000.

**Comment by janoside** [comment]
Too long for this to get fixed, but today's large mempool provided some inspiration at the right moment when I had some bandwidth to spare. Please enjoy this long-overdue improvement/bug fix.
