### ISSUE TITLE
JavaScript heap out of memory

### ISSUE THREAD

**Issue by sangaman** [janoside/btc-rpc-explorer#133]
btc-rpc-explorer sometimes crashes while running but not actively serving webpages with `FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory`

**Environment:**
 - Bitcoin Core 18.0
 - NodeJS 10.15.3
 - Code Version / Commit [e.g. ab6cde8]
 - 2 GB RAM with 4 GB swap

**Screenshots or Log Output**

```
<--- Last few GCs --->

[7042:0x1b4ce58] 11672336 ms: Mark-sweep 698.2 (723.9) -> 698.2 (724.9) MB, 9005.3 / 0.0 ms  (average mu = 0.076, current mu = 0.001) allocation failure scavenge might not succeed


<--- JS stacktrace --->

==== JS stack trace =========================================

    0: ExitFrame [pc: 0x2576ae9c]
Security context: 0x22d12705 <JSObject>
    1: handleWriteReq(aka handleWriteReq) [0x5c58b675] [internal/stream_base_commons.js:23] [bytecode=0x5d3d9199 offset=139](this=0x2098438d <undefined>,req=0x29ce37a1 <WriteWrap map = 0x3e6301b1>,data=0x29ce3765 <Very long string[199423]>,encoding=0x22d23d99 <String[4]: utf8>)
    2: writeGeneric(aka writeGeneric) [0x5c589185] [internal/stream_base_commons.js:71] [...

FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
Aborted
```

**Comment by janoside** [comment]
It's been a long time. I don't have a good understanding of why there would be crashes when not actively serving pages, but there were some major improvements to some of the high-memory codepaths made for v2.0.0. I'd be curious to hear about your experience running the latest code.

**Comment by sangaman** [comment]
I've been running the latest code for a little while now and just stress tested it a bit by pulling up an address with a lot of transactions and the mempool summary, and everything is working fine. I also have to say I haven't seen this crash happen in a while over months of light use. I'll close this since it doesn't seem to be an active issue currently.

**Comment by sangaman** [comment]
I've seen this happen twice now in the past few days, which is more often than I recall it happening with older versions.

```

{"name":"bitcoin-core","hostname":"thundroid","pid":16764,"level":20,"request":{"duration":11971,"error":{"code":"ESOCKETTIMEDOUT","connect":false},"headers":{"host":"localhost:8332","authorization":"Basic ******","content-length":135},"id":"951970dd-7266-4ebe-9194-352be36fc214","method":"POST","type":"error","uri":"http://localhost:8332/"},"msg":"Making request 951970dd-7266-4ebe-9194-352be36fc214 to POST http://localhost:8332/","time":"2020-03-30T16:38:25.487Z","v":0}
  btcexp:error Error 38eh39hdee: Error: ESOCKETTIMEDOUT, json: {"cause":{"code":"ESOCKETTIMEDOUT","connect":false},"isOperational":true,"code":"ESOCKETTIMEDOUT","connect":false}, userData: [object Object] (json: {}) +2m
  btcexp:errorVerbose Stack: Error: ESOCKETTIMEDOUT
  btcexp:errorVerbose     at ClientRequest.<anonymous> (/home/bitcoin/btc-rpc-explorer/node_modules/request/request.js:816:19)
  btcexp:errorVerbose     at Object.onceWrapper (events.js:286:20)
  btcexp:errorVerbose     at ClientRequest.emit (events.js:198:13)
  btcexp:errorVerbose     at Socket.emitRequestTimeout (_http_client.js:673:40)
  btcexp:errorVerbose     at Object.onceWrapper (events.js:286:20)
  btcexp:errorVerbose     at Socket.emit (events.js:198:13)
  btcexp:errorVerbose     at Socket._onTimeout (net.js:443:8)
  btcexp:errorVerbose     at ontimeout (timers.js:436:11)
  btcexp:errorVerbose     at tryOnTimeout (timers.js:300:5)
  btcexp:errorVerbose     at listOnTimeout (timers.js:263:5)
  btcexp:errorVerbose     at Timer.processTimers (timers.js:223:10) +2m

<--- Last few GCs --->

[16764:0x1cd4160] 220537317 ms: Mark-sweep 700.8 (727.4) -> 700.8 (727.9) MB, 11185.6 / 0.1 ms  (+ 16.7 ms in 7 steps since start of marking, biggest step 6.8 ms, walltime since start of marking 11219 ms) (average mu = 0.140, current mu = 0.002) allocatio[16764:0x1cd4160] 220549323 ms: Mark-sweep 701.5 (727.9) -> 700.1 (727.9) MB, 11521.1 / 0.0 ms  (+ 404.5 ms in 202 steps since start of marking, biggest step 4.7 ms, walltime since start of marking 12005 ms) (average mu = 0.075, current mu = 0.007) alloca

<--- JS stacktrace --->

FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
Aborted
npm ERR! code ELIFECYCLE
npm ERR! errno 134
npm ERR! btc-rpc-explorer@2.0.0 start: `node ./bin/www`
npm ERR! Exit status 134
npm ERR!
npm ERR! Failed at the btc-rpc-explorer@2.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/bitcoin/.npm/_logs/2020-03-30T16_38_36_523Z-debug.log
```

And from the most recent time it happened:

```
  express:view lookup "index.pug" +8s
  express:view stat "/home/bitcoin/btc-rpc-explorer/views/index.pug" +0ms
  express:view render "/home/bitcoin/btc-rpc-explorer/views/index.pug" +5ms

<--- Last few GCs --->

[25953:0x1cd4160] 225781460 ms: Scavenge 695.9 (722.9) -> 695.8 (723.9) MB, 51.9 / 0.0 ms  (average mu = 0.148, current mu = 0.028) allocation failure
[25953:0x1cd4160] 225788559 ms: Mark-sweep 696.4 (723.9) -> 696.2 (723.9) MB, 7045.5 / 0.0 ms  (average mu = 0.102, current mu = 0.020) allocation failure scavenge might not succeed


<--- JS stacktrace --->

==== JS stack trace =========================================

    0: ExitFrame [pc: 0x4d0eae9c]
    1: StubFrame [pc: 0x4d0ec040]
Security context: 0x28112705 <JSObject>
    2: /* anonymous */ [0x40b327b1] [/home/bitcoin/btc-rpc-explorer/node_modules/acorn-globals/node_modules/acorn/dist/acorn.js:~3182] [pc=0x990a2d64](this=0x24a84101 <Parser map = 0x560c092d>,quote=34)
    3: /* anonymous */ [0x40b32509] [/home/bitcoin/btc-rpc-explorer/node_modules/acorn-globals/node_modules/acorn/dist/acorn.js:~29...

FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
Aborted
npm ERR! code ELIFECYCLE
npm ERR! errno 134
npm ERR! btc-rpc-explorer@2.0.0 start: `node ./bin/www`
npm ERR! Exit status 134
npm ERR!
npm ERR! Failed at the btc-rpc-explorer@2.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

**Comment by sangaman** [comment]
Still seeing this on most recent commit:

```
  express:view lookup "mempool-summary.pug" +32s
  express:view stat "/home/bitcoin/btc-rpc-explorer/views/mempool-summary.pug" +13ms
  express:view render "/home/bitcoin/btc-rpc-explorer/views/mempool-summary.pug" +108ms

<--- Last few GCs --->

[6139:0x1cda700] 1457399836 ms: Scavenge 693.0 (719.1) -> 693.0 (720.1) MB, 64.1 / 0.0 ms  (average mu = 0.189, current mu = 0.149) allocation failure
[6139:0x1cda700] 1457399933 ms: Scavenge 693.7 (720.1) -> 693.6 (721.1) MB, 58.3 / 0.0 ms  (average mu = 0.189, current mu = 0.149) allocation failure
[6139:0x1cda700] 1457400155 ms: Scavenge 696.9 (722.8) -> 696.9 (723.8) MB, 68.1 / 0.0 ms  (average mu = 0.189, current mu = 0.149) allocation failure


<--- JS stacktrace --->

==== JS stack trace =========================================

Security context: 0x23a926ed <JSObject>
    0: builtin exit frame: stringify(this=0x23a8c039 <Object map = 0x2db85155>,0x3fa8438d <undefined>,0x3fa8438d <undefined>,0xae47db91 <JSArray[974]>,0x23a8c039 <Object map = 0x2db85155>)

    1: arguments adaptor frame: 1->3
    2: /* anonymous */ [0x3d5041c5] [0x3fa8438d <undefined>:1441] [bytecode=0x9b345ce9 offset=13429](this=0x52d04609 <JSGlobal Object>,JSON=0x23a8c039 <Object map = 0x2db85155...

FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
Aborted
```

**Comment by sangaman** [comment]
Still a frequent issue for me, it seems to crash due to Javascript heap out of memory even when I'm not interacting with the explorer but just don't visit it for a few days.

**Comment by janoside** [comment]
Thanks for the update. Will try to prioritize a deeper investigation.

**Comment by sangaman** [comment]
Here's another snippet from a recent crash in case it helps.

```
[huge json object from a getRawTransaction call]
"headers":{"content-type":"application/json","date":"Wed, 06 Jan 2021 23:29:19 GMT","content-length":"2037","connection":"
close"},"id":"38f58a3b-03d3-4e6b-9ec1-a2cf45ec20e9","statusCode":200,"type":"response","uri":"http://localhost:8332/"},"msg":"Received response for request 38f58a3b-03d3-4e6b-9ec1-a2cf45ec20e9","time":"2021-01-06T23:29:19.191Z","v":0}
  express:view lookup "index.pug" +8s
  express:view stat "/home/bitcoin/btc-rpc-explorer/views/index.pug" +0ms
  express:view render "/home/bitcoin/btc-rpc-explorer/views/index.pug" +3ms

<--- Last few GCs --->

[2249:0x3834430] 89842906 ms: Mark-sweep (reduce) 497.7 (499.3) -> 497.5 (501.1) MB, 7286.2 / 0.1 ms  (average mu = 0.147, current mu = 0.014) allocation failure scavenge might not succeed
[2249:0x3834430] 89856204 ms: Mark-sweep (reduce) 498.0 (501.1) -> 497.9 (501.3) MB, 9939.4 / 0.1 ms  (average mu = 0.212, current mu = 0.253) allocation failure scavenge might not succeed

```

**Comment by janoside** [comment]
Cleaning up old issues. If you're still having this problem using the latest code (3.4-beta or greater), feel free to reply.
