### ISSUE TITLE
Error: Non-base58 character

### ISSUE THREAD

**Issue by HamishMacEwan** [janoside/btc-rpc-explorer#143]
I've configured a local Electrumrs server with: `BTCEXP_ELECTRUMX_SERVERS=tls://192.168.1.141:50002`

This url displays the expected information as far as I can tell:
http://192.168.1.100:3002/address/bc1q6we7fpmwwfx57qpattnlwttm8lymdt3vfxrex40ju98dpqen0g0sq0e47z

![Channel Point bc1q6we7fpmwwfx57qpattnlwttm8lymdt3vfxrex40ju98dpqen0g0sq0e47z Capture](https://user-images.githubusercontent.com/388061/64073719-a80d2b80-ccf5-11e9-80e5-fcdec7a27d39.JPG)

However: 

Stacktrace
```
Error: Non-base58 character
    at Object.decode (/usr/local/lib/node_modules/btc-rpc-explorer/node_modules/base-x/index.js:84:11)
    at Object.decode (/usr/local/lib/node_modules/btc-rpc-explorer/node_modules/bs58check/base.js:39:25)
    at Object.fromBase58Check (/usr/local/lib/node_modules/btc-rpc-explorer/node_modules/bitcoinjs-lib/src/address.js:11:27)
    at /usr/local/lib/node_modules/btc-rpc-explorer/routes/baseActionsRouter.js:613:45
    at Layer.handle [as handle_request] (/usr/local/lib/node_modules/btc-rpc-explorer/node_modules/express/lib/router/layer.js:95:5)
    at next (/usr/local/lib/node_modules/btc-rpc-explorer/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/usr/local/lib/node_modules/btc-rpc-explorer/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/usr/local/lib/node_modules/btc-rpc-explorer/node_modules/express/lib/router/layer.js:95:5)
    at /usr/local/lib/node_modules/btc-rpc-explorer/node_modules/express/lib/router/index.js:281:22
    at param (/usr/local/lib/node_modules/btc-rpc-explorer/node_modules/express/lib/router/index.js:354:14)
    at param (/usr/local/lib/node_modules/btc-rpc-explorer/node_modules/express/lib/router/index.js:365:14)
    at Function.process_params (/usr/local/lib/node_modules/btc-rpc-explorer/node_modules/express/lib/router/index.js:410:3)
    at next (/usr/local/lib/node_modules/btc-rpc-explorer/node_modules/express/lib/router/index.js:275:10)
    at Function.handle (/usr/local/lib/node_modules/btc-rpc-explorer/node_modules/express/lib/router/index.js:174:3)
    at router (/usr/local/lib/node_modules/btc-rpc-explorer/node_modules/express/lib/router/index.js:47:12)
    at Layer.handle [as handle_request] (/usr/local/lib/node_modules/btc-rpc-explorer/node_modules/express/lib/router/layer.js:95:5)
```

**Comment by janoside** [comment]
@HamishMacEwan This should be fixed now. If you update and you still see this, please let me know.
