### ISSUE TITLE
cannot connect to remote deamon of new forked coin of litecoin

### ISSUE THREAD

**Issue by vanshtah** [janoside/btc-rpc-explorer#147]
**Describe the bug**
cannot connect to remote deamon of new forked coin of litecoin

**Environment (please complete the following information):**
 - litecoin v0.15
 - 10.x
 - chrome

When i npm start below error occured,

```
  btcexp:app Running RPC Explorer for Litecoin +0ms
  btcexp:app Connecting via RPC to node at 127.0.0.1:9789 +1ms
  btcexp:error Error 32euofeege: Error: socket hang up, json: {"cause":{"code":"ECONNRESET"},"isOperational":true,"code":"ECONNRESET"}, userData: [object Object] (json: {"cmd":"getnetworkinfo"}) +0ms
  btcexp:error Stack: Error: socket hang up
  btcexp:error     at createHangUpError (_http_client.js:330:17)
  btcexp:error     at Socket.socketOnEnd (_http_client.js:431:23)
  btcexp:error     at Socket.emit (events.js:198:15)
  btcexp:error     at endReadableNT (_stream_readable.js:1139:12)
  btcexp:error     at processTicksAndRejections (internal/process/task_queues.js:81:17) +0ms
  btcexp:error Error 32ugegdfsde: Error: socket hang up, json: {"cause":{"code":"ECONNRESET"},"isOperational":true,"code":"ECONNRESET"} +0ms
  btcexp:error Stack: Error: socket hang up
  btcexp:error     at createHangUpError (_http_client.js:330:17)
  btcexp:error     at Socket.socketOnEnd (_http_client.js:431:23)
  btcexp:error     at Socket.emit (events.js:198:15)
  btcexp:error     at endReadableNT (_stream_readable.js:1139:12)
  btcexp:error     at processTicksAndRejections (internal/process/task_queues.js:81:17) +0ms
```

my .env file 

```
# Optional logging settings, see comments after each for more info
#DEBUG=*  # Enable all logging, including middleware, etc
#DEBUG=btcexp:*  # Enable all logging specific to btc-rpc-explorer
#DEBUG=btcexp:app,btcexp:error  # Default logging setting if "DEBUG" is not set

# The active coin: BTC/LTC
BTCEXP_COIN=LTC

# Host/Port to bind to
#BTCEXP_HOST=127.0.0.1
#BTCEXP_PORT=3002

# Bitcoin RPC Credentials (URI -OR- HOST/PORT/USER/PASS)
#BTCEXP_BITCOIND_URI=bitcoin://rpcusername:rpcpassword@127.0.0.1:8332?timeout=10000
BTCEXP_BITCOIND_HOST=174.138.27.171
BTCEXP_BITCOIND_PORT=9789
BTCEXP_BITCOIND_USER=vanshtah
BTCEXP_BITCOIND_PASS=1234567890
#BTCEXP_BITCOIND_COOKIE=/path/to/bitcoind/.cookie
BTCEXP_BITCOIND_RPC_TIMEOUT=5000

# Select optional "address API" to display address tx lists and balances
# Options: electrumx, blockchain.com, blockchair.com, blockcypher.com
# If electrumx set, the BTCEXP_ELECTRUMX_SERVERS variable must also be
# set.
#BTCEXP_ADDRESS_API=(electrumx|blockchain.com|blockcypher.com)

# Optional ElectrumX Servers. See BTCEXP_ADDRESS_API. This value is only
# used if BTCEXP_ADDRESS_API=electrumx
#BTCEXP_ELECTRUMX_SERVERS=tls://electrumx.server.com:50002,tcp://127.0.0.1:50001,...

# Set number of concurrent RPC requests. Should be lower than your node's "rpcworkqueue" value.
# The default for this value is 10, aiming to be less than Bitcoin Core's default rpcworkqueue=16.
#BTCEXP_RPC_CONCURRENCY=10

# Disable app's in-memory RPC caching to reduce memory usage
#BTCEXP_NO_INMEMORY_RPC_CACHE=true

# Optional redis server for RPC caching
#BTCEXP_REDIS_URL=redis://localhost:6379

#BTCEXP_COOKIE_SECRET=0000aaaafffffgggggg

# Whether public-demo aspects of the site are active
#BTCEXP_DEMO=true

# Privacy mode disables:
# Exchange-rate queries, IP-geolocation queries
#BTCEXP_PRIVACY_MODE=true

# Don't request currency exchange rates
#BTCEXP_NO_RATES=true

# Password protection for site via basic auth (enter any username, only the password is checked)
#BTCEXP_BASIC_AUTH_PASSWORD=mypassword

# Enable to allow access to all RPC methods
#BTCEXP_RPC_ALLOWALL=true

# Custom RPC method blacklist
#BTCEXP_RPC_BLACKLIST=signrawtransaction,sendtoaddress,stop,...

#BTCEXP_GANALYTICS_TRACKING=UA-XXXX-X
#BTCEXP_SENTRY_URL=https://00000fffffff@sentry.io/XXXX
#BTCEXP_IPSTACK_APIKEY=000000fffffaaaaa

# Optional value for "max_old_space_size", default: 1024
#BTCEXP_OLD_SPACE_MAX_SIZE=2048

# Show tools list in a sub-nav at top of screen (default: true)
BTCEXP_UI_SHOW_TOOLS_SUBHEADER=true
```

**Comment by janoside** [comment]
Hmmm, looks like a networking issue, probably unrelated to the code for this project. @vanshtah  Have you verified your ability to connect to your node from any other software? My guess is that you'll need to tweak your networking settings on your remote host to allow connections to the node running on it.

**Comment by vanshtah** [comment]
> Hmmm, looks like a networking issue, probably unrelated to the code for this project. @vanshtah Have you verified your ability to connect to your node from any other software? My guess is that you'll need to tweak your networking settings on your remote host to allow connections to the node running on it.

Can you please help me with the .conf file for connection

**Comment by janoside** [comment]
Glad you got your connection issue resolve. This new error is likely related to your node.js version. Can you check what version of node.js you're running locally?

**Comment by vanshtah** [comment]
> Glad you got your connection issue resolve. This new error is likely related to your node.js version. Can you check what version of node.js you're running locally?

nodejs: v11.15.0
npm: 6.11.3

**Comment by janoside** [comment]
Well, your node.js and npm versions look good. Now we may be getting to issues related to RPC API differences between bitcoin and whatever coin you're trying to use. Unfortunately I'm not going to be able to help you with issues like that. I initially supported LTC because it was easy to do so, but have dropped support for simplicity's sake as LTC lags behind BTC and differs in other small ways. I welcome you to fork this explorer and tweak as needed to make sure that it works with any coin you wish. An easy fix for this particular issue might be to simply delete the line in `index.pug` that's throwing an error (line 101). But I can't speak to any further errors you might encounter.

I'm closing this issue, but feel free to reply if you believe you're encountering bugs/errors that are present in use of the tool with BTC as well.
