### ISSUE TITLE
Problem in rpcAPI.js

### ISSUE THREAD

**Issue by vanshtah** [janoside/btc-rpc-explorer#156]
`Unhandled Rejection at: Promise Promise {
  <rejected> TypeError: Cannot read property '0' of undefined
    at /home/vanshtah/btc-rpc-explorer/app/api/rpcApi.js:129:30
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7) } reason: TypeError: Cannot read property '0' of undefined
    at /home/vanshtah/btc-rpc-explorer/app/api/rpcApi.js:129:30
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7) stack: TypeError: Cannot read property '0' of undefined
    at /home/vanshtah/btc-rpc-explorer/app/api/rpcApi.js:129:30
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7) +44ms`

I am unable to see the homepage in localhost:3002 and above error is displayed in Terminal

**Comment by janoside** [comment]
@vanshtah Please update to the latest code (v1.1.4) and let me know if you're still seeing this error. If you are, please give me all the info about your setup that's requested in the new-issue template. Thanks.

**Comment by janoside** [comment]
Closing for now. Happy to continue discussion here if needed.
