### ISSUE TITLE
Does not work with BTC 0.19

### ISSUE THREAD

**Issue by Warchant** [janoside/btc-rpc-explorer#160]
**Describe the bug**

When open default page:
```
  btcexp:app Unhandled Rejection at: Promise Promise {
  <rejected> TypeError: Cannot read property '0' of undefined
      at /home/bogdan/.config/yarn/global/node_modules/btc-rpc-explorer/app/api/rpcApi.js:129:30
      at process.internalTickCallback (internal/process/next_tick.js:77:7) } reason: TypeError: Cannot read property '0' of undefined
    at /home/bogdan/.config/yarn/global/node_modules/btc-rpc-explorer/app/api/rpcApi.js:129:30
    at process.internalTickCallback (internal/process/next_tick.js:77:7) stack: TypeError: Cannot read property '0' of undefined
    at /home/bogdan/.config/yarn/global/node_modules/btc-rpc-explorer/app/api/rpcApi.js:129:30
    at process.internalTickCallback (internal/process/next_tick.js:77:7) +10s
```

When go to Browse Blocks:
```
    message:
     'No such mempool or blockchain transaction. Use gettransaction for wallet transactions.',
    code: -5,
    name: 'RpcError' } } reason: { RpcError: No such mempool or blockchain transaction. Use gettransaction for wallet transactions.
    at getRpcResult (/home/bogdan/.config/yarn/global/node_modules/bitcoin-core/dist/src/parser.js:39:11)
    at body.map.response (/home/bogdan/.config/yarn/global/node_modules/bitcoin-core/dist/src/parser.js:91:16)
    at Array.map (<anonymous>)
    at Client.rpc (/home/bogdan/.config/yarn/global/node_modules/bitcoin-core/dist/src/parser.js:89:24)
    at Client.tryCatcher (/home/bogdan/.config/yarn/global/node_modules/bitcoin-core/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/bogdan/.config/yarn/global/node_modules/bitcoin-core/node_modules/bluebird/js/release/promise.js:547:31)
    at Promise._settlePromise (/home/bogdan/.config/yarn/global/node_modules/bitcoin-core/node_modules/bluebird/js/release/promise.js:604:18)
    at Promise._settlePromise0 (/home/bogdan/.config/yarn/global/node_modules/bitcoin-core/node_modules/bluebird/js/release/promise.js:649:10)
    at Promise._settlePromises (/home/bogdan/.config/yarn/global/node_modules/bitcoin-core/node_modules/bluebird/js/release/promise.js:729:18)
    at Promise._fulfill (/home/bogdan/.config/yarn/global/node_modules/bitcoin-core/node_modules/bluebird/js/release/promise.js:673:18)
    at Request._callback (/home/bogdan/.config/yarn/global/node_modules/bitcoin-core/node_modules/bluebird/js/release/nodeback.js:45:21)
    at Request.self.callback (/home/bogdan/.config/yarn/global/node_modules/request/request.js:185:22)
    at Request.emit (events.js:187:15)
    at Request.<anonymous> (/home/bogdan/.config/yarn/global/node_modules/request/request.js:1161:10)
    at Request.emit (events.js:182:13)
    at IncomingMessage.<anonymous> (/home/bogdan/.config/yarn/global/node_modules/request/request.js:1083:12)
    at Object.onceWrapper (events.js:273:13)
    at IncomingMessage.emit (events.js:187:15)
    at endReadableNT (_stream_readable.js:1094:12)
    at process.internalTickCallback (internal/process/next_tick.js:72:19)
  message:
   'No such mempool or blockchain transaction. Use gettransaction for wallet transactions.',
  code: -5,
  name: 'RpcError' } stack: RpcError: No such mempool or blockchain transaction. Use gettransaction for wallet transactions.
    at getRpcResult (/home/bogdan/.config/yarn/global/node_modules/bitcoin-core/dist/src/parser.js:39:11)
    at body.map.response (/home/bogdan/.config/yarn/global/node_modules/bitcoin-core/dist/src/parser.js:91:16)
    at Array.map (<anonymous>)
    at Client.rpc (/home/bogdan/.config/yarn/global/node_modules/bitcoin-core/dist/src/parser.js:89:24)
    at Client.tryCatcher (/home/bogdan/.config/yarn/global/node_modules/bitcoin-core/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/bogdan/.config/yarn/global/node_modules/bitcoin-core/node_modules/bluebird/js/release/promise.js:547:31)
    at Promise._settlePromise (/home/bogdan/.config/yarn/global/node_modules/bitcoin-core/node_modules/bluebird/js/release/promise.js:604:18)
    at Promise._settlePromise0 (/home/bogdan/.config/yarn/global/node_modules/bitcoin-core/node_modules/bluebird/js/release/promise.js:649:10)
    at Promise._settlePromises (/home/bogdan/.config/yarn/global/node_modules/bitcoin-core/node_modules/bluebird/js/release/promise.js:729:18)
    at Promise._fulfill (/home/bogdan/.config/yarn/global/node_modules/bitcoin-core/node_modules/bluebird/js/release/promise.js:673:18)
    at Request._callback (/home/bogdan/.config/yarn/global/node_modules/bitcoin-core/node_modules/bluebird/js/release/nodeback.js:45:21)
    at Request.self.callback (/home/bogdan/.config/yarn/global/node_modules/request/request.js:185:22)
    at Request.emit (events.js:187:15)
    at Request.<anonymous> (/home/bogdan/.config/yarn/global/node_modules/request/request.js:1161:10)
    at Request.emit (events.js:182:13)
    at IncomingMessage.<anonymous> (/home/bogdan/.config/yarn/global/node_modules/request/request.js:1083:12)
    at Object.onceWrapper (events.js:273:13)
    at IncomingMessage.emit (events.js:187:15)
    at endReadableNT (_stream_readable.js:1094:12)
    at process.internalTickCallback (internal/process/next_tick.js:72:19) +1m
```

**Environment (please complete the following information):**

 - Bitcoin Core / Node Version 0.19
 - NodeJS Version 11.x
 - Browser: any
 - Code Version: 195874987191fd68c50dcba967d8833d992e5b60

**To Reproduce**

1. Deploy BTC 0.19, any mode (regtest/testnet/mainnet)
2. Deploy BTC-RPC-Explorer pointing to BTC 0.19
3. Go to main page, go to "Browse blocks"
4. See errors in explorer daemon

**Screenshots or Log Output**

If applicable, add screenshots or log output to help explain your problem.
![image](https://user-images.githubusercontent.com/1867551/69871093-8acb0780-12ba-11ea-8faf-37226e1e3272.png)

**Comment by janoside** [comment]
Hmmm, not able to reproduce this. Just updated to 0.19.0.1 and the app seems to be working fine. I'm also running at commit #1958749

I'll keep thinking about this but let me know if anything changes for you.

**Comment by Warchant** [comment]
Try on regtest

**Comment by janoside** [comment]
Ok. Will work on setting up regtest env. In the meantime, can you confirm that this app worked on "regtest with 0 blocks" on 0.18?

**Comment by Warchant** [comment]
I can confirm that there are other issues, related to "fresh" install in regtest. With 0 peers (and regtest has 0 peers), explorer also "dies" on page "Peers"

**Comment by janoside** [comment]
Hey @Warchant - got my regtest env set up. I was able to reproduce the error on `/peers` right away. I wasn't getting errors for other things though. Regardless, I thought that first-class support for testnet/regtest should be completed, and now it has. Please check out the latest updates in v1.1.4 and let me know if you're still having problems here.

**Comment by Warchant** [comment]
It is okay for now. Thanks.
