### ISSUE TITLE
'OnError:Error: connect ECONNREFUSED' too verbose

### ISSUE THREAD

**Issue by schildbach** [janoside/btc-rpc-explorer#171]
**Describe the bug**

Every 10 seconds, until the connection to electrumx has been verified, I get this in my log:

```
Dec 23 09:05:13 nas docker-compose[21360]: btc-rpc-explorer_1  | OnError:Error: connect ECONNREFUSED 192.168.16.3:51001
Dec 23 09:05:13 nas docker-compose[21360]: btc-rpc-explorer_1  | 2019-12-23T09:05:13.731Z btcexp:app Unhandled Rejection at: Promise Promise
Dec 23 09:05:13 nas docker-compose[21360]: btc-rpc-explorer_1  |   <rejected> { Error: connect ECONNREFUSED 192.168.16.3:51001
Dec 23 09:05:13 nas docker-compose[21360]: btc-rpc-explorer_1  |     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1191:14)
Dec 23 09:05:13 nas docker-compose[21360]: btc-rpc-explorer_1  |   errno: 'ECONNREFUSED',
Dec 23 09:05:13 nas docker-compose[21360]: btc-rpc-explorer_1  |   code: 'ECONNREFUSED',
Dec 23 09:05:13 nas docker-compose[21360]: btc-rpc-explorer_1  |   syscall: 'connect',
Dec 23 09:05:13 nas docker-compose[21360]: btc-rpc-explorer_1  |   address: '192.168.16.3',
Dec 23 09:05:13 nas docker-compose[21360]: btc-rpc-explorer_1  |   port: 51001 } } reason: { Error: connect ECONNREFUSED 192.168.16.3:51001
Dec 23 09:05:13 nas docker-compose[21360]: btc-rpc-explorer_1  |     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1191:14)
Dec 23 09:05:13 nas docker-compose[21360]: btc-rpc-explorer_1  |   errno: 'ECONNREFUSED',
Dec 23 09:05:13 nas docker-compose[21360]: btc-rpc-explorer_1  |   code: 'ECONNREFUSED',
Dec 23 09:05:13 nas docker-compose[21360]: btc-rpc-explorer_1  |   syscall: 'connect',
Dec 23 09:05:13 nas docker-compose[21360]: btc-rpc-explorer_1  |   address: '192.168.16.3',
Dec 23 09:05:13 nas docker-compose[21360]: btc-rpc-explorer_1  |   port: 51001 } stack: Error: connect ECONNREFUSED 192.168.16.3:51001
Dec 23 09:05:13 nas docker-compose[21360]: btc-rpc-explorer_1  |     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1191:14)
Dec 23 09:05:13 nas docker-compose[21360]: btc-rpc-explorer_1  | OnClose:undefined
```

Similar to #169 and #170, I think this can be much less verbose, e.g. a one-liner.

Or perhaps they should not happen at all, since they don't seem to be part of the new verifyRpcConnection() loop introduced in f23e0295485e1f0dc04b8af8e85d437558a6af54.

**Environment (please complete the following information):**

 - Code Version / Commit: 9d64902
 - running inside Docker, using the supplied Dockerfile

**Comment by janoside** [comment]
Happily, this was fixed as a byproduct of improvements for #188.
