### ISSUE TITLE
tiny-secp256k1 module error on npm install

### ISSUE THREAD

**Issue by k3tan172** [janoside/btc-rpc-explorer#186]
During installation, I'm getting errors with the tiny-secp256k1 module.
There is no impact on the successful installation of btc-rpc-explorer, but just wanted to report to see if it can be solved. Below is the excerpt of the error I see upon ```npm install -g btc-rpc-explorer```.

```
make: Entering directory '/home/ketan/.npm-global/lib/node_modules/btc-rpc-explorer/node_modules/tiny-secp256k1/build'
  CXX(target) Release/obj.target/secp256k1/native/addon.o
make: g++: Command not found
make: *** [secp256k1.target.mk:153: Release/obj.target/secp256k1/native/addon.o] Error 127
make: Leaving directory '/home/ketan/.npm-global/lib/node_modules/btc-rpc-explorer/node_modules/tiny-secp256k1/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:311:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
gyp ERR! System Linux 4.19.0-8-amd64
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/ketan/.npm-global/lib/node_modules/btc-rpc-explorer/node_modules/tiny-secp256k1
gyp ERR! node -v v12.16.1
gyp ERR! node-gyp -v v5.0.5
gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! tiny-secp256k1@1.1.3 build: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the tiny-secp256k1@1.1.3 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/ketan/.npm/_logs/2020-03-01T19_53_04_276Z-debug.log
secp256k1 bindings compilation fail. Pure JS implementation will be used.
```

**Comment by ser** [comment]
```make: g++: Command not found``` 

just install c++ builder environment

**Comment by k3tan172** [comment]
Thank you!
