### ISSUE TITLE
Undefined properties in release 2.0.0

### ISSUE THREAD

**Issue by Pantamis** [janoside/btc-rpc-explorer#197]
**Describe the bug**

Abort when connecting to the explorer with the browser with the following error :

```
TypeError: /home/btcrpcexplorer/btc-rpc-explorer/views/layout.pug:39
    37| 							img.header-image(src="/img/logo/btc.svg", alt="logo")
    38| 
  > 39| 						span #{coinConfig.siteTitlesByNetwork[global.activeBlockchain]}
    40| 						
    41| 				button.navbar-toggler.navbar-toggler-right(type="button", data-toggle="collapse", data-target="#navbarNav", aria-label="collapse navigation")
    42| 					span.navbar-toggler-icon

Cannot read property 'main' of undefined
    at eval (eval at wrap (/home/btcrpcexplorer/btc-rpc-explorer/node_modules/pug-runtime/wrap.js:6:10), <anonymous>:73:87)
    at template (eval at wrap (/home/btcrpcexplorer/btc-rpc-explorer/node_modules/pug-runtime/wrap.js:6:10), <anonymous>:1269:72)
    at Object.exports.renderFile (/home/btcrpcexplorer/btc-rpc-explorer/node_modules/pug/lib/index.js:427:38)
    at Object.exports.renderFile (/home/btcrpcexplorer/btc-rpc-explorer/node_modules/pug/lib/index.js:417:21)
    at exports.__express (/home/btcrpcexplorer/btc-rpc-explorer/node_modules/pug/lib/index.js:464:11)
    at View.app.engine (/home/btcrpcexplorer/btc-rpc-explorer/app.js:63:23)
    at View.render (/home/btcrpcexplorer/btc-rpc-explorer/node_modules/express/lib/view.js:135:8)
    at tryRender (/home/btcrpcexplorer/btc-rpc-explorer/node_modules/express/lib/application.js:640:10)
    at Function.render (/home/btcrpcexplorer/btc-rpc-explorer/node_modules/express/lib/application.js:592:3)
    at ServerResponse.render (/home/btcrpcexplorer/btc-rpc-explorer/node_modules/express/lib/response.js:1012:7)
    at /home/btcrpcexplorer/btc-rpc-explorer/app.js:483:6
    at Layer.handle_error (/home/btcrpcexplorer/btc-rpc-explorer/node_modules/express/lib/router/layer.js:71:5)
    at trim_prefix (/home/btcrpcexplorer/btc-rpc-explorer/node_modules/express/lib/router/index.js:315:13)
    at /home/btcrpcexplorer/btc-rpc-explorer/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/home/btcrpcexplorer/btc-rpc-explorer/node_modules/express/lib/router/index.js:335:12)
    at IncomingMessage.next (/home/btcrpcexplorer/btc-rpc-explorer/node_modules/express/lib/router/index.js:275:10)

```
**Environment (please complete the following information):**

 - Bitcoin Core 0.19.1
 - NodeJS Version 12
 - Browser : Brave (Chromium based)
 - Code Version / Commit 87ce1e411b419f7fd77399e7bbd61d4ff5d52008
 
**To Reproduce**

Run the explorer and connect to it with browser. Return the print of the log above in browser

**Additional context**

Downgrade to v1.1.9 works. 
When deleting the line `span #{coinConfig.siteTitlesByNetwork[global.activeBlockchain]}` it does not start with the same kind of error message at a different line so it seems that the definition of something is missing in v2.0.0

Thanks for your amazing work on this project :)

**Comment by janoside** [comment]
Hmm, this has me stumped. Not sure how you're missing that. Are you running this for a non-BTC coin?

By the way, glad you value the project!

**Comment by Pantamis** [comment]
I run a BTC node on a RaspiBolt

I deleted the project folder and cloned it again. It works well now with current master or release so I don't understand what causes this error. Maybe something related to the configuration file, even if I carefully put the same settings. I also use NginX to create a SSL bridge so maybe I had some trouble with the listening port...

I close the issue, thanks for your time !
