### ISSUE TITLE
getblockstats Issue

### ISSUE THREAD

**Issue by knkrth** [janoside/btc-rpc-explorer#201]
`getblockstats` sends a negative block height to the JSON request.

```
btc-rpc-explorer$ npm start

> btc-rpc-explorer@2.0.0 start /home/workspace/btc-rpc-explorer
> node ./bin/www

Loading env file: /home/workspace/btc-rpc-explorer/.env
  btcexp:app Starting BTC RPC Explorer, v2.0.0 (commit: '8cf258182b', date: 2020-03-28) +0ms
  btcexp:app Connecting to RPC node at 127.0.0.1:8332 +3ms
  btcexp:app Verifying RPC connection... +43ms
  btcexp:app Loading mining pools config +3ms
  btcexp:app RPC Connected: version=190100 subversion=/Satoshi:0.19.1/, parsedVersion(used for RPC versioning)=0.19.1, protocolversion=70015, chain=main, services=[NETWORK, WITNESS, NETWORK_LIMITED] +50ms
  btcexp:app Loading historical data for chain=main +1ms
  btcexp:app Skipping performance-intensive task: fetch UTXO set summary. This is skipped due to the flag 'slowDeviceMode' which defaults to 'true' to protect slow nodes. Set this flag to 'false' to enjoy UTXO set summary details. +1ms
  btcexp:error Error 283h7ewsede: Error: RpcError: type=errorResponse-03, json: {"userData":{"error":null,"request":{"method":"getblockstats","parameters":[-1]},"result":[{"message":"Target block height -1 is negative","code":-8,"name":"RpcError"}]}}, userData: [object Object] (json: {"error":null,"request":{"method":"getblockstats","parameters":[-1]},"result":[{"message":"Target block height -1 is negative","code":-8,"name":"RpcError"}]}) +0ms
  btcexp:app Unhandled Rejection at: Promise Promise {
  <rejected> { Error: RpcError: type=errorResponse-03
      at Client.<anonymous> (/home/workspace/btc-rpc-explorer/app/api/rpcApi.js:420:14)
      at Client.tryCatcher (/home/workspace/btc-rpc-explorer/node_modules/bluebird/js/release/util.js:16:23)
      at Promise.successAdapter (/home/workspace/btc-rpc-explorer/node_modules/bluebird/js/release/nodeify.js:23:30)
      at Promise._settlePromise (/home/workspace/btc-rpc-explorer/node_modules/bluebird/js/release/promise.js:601:21)
      at Promise._settlePromise0 (/home/workspace/btc-rpc-explorer/node_modules/bluebird/js/release/promise.js:649:10)
      at Promise._settlePromises (/home/workspace/btc-rpc-explorer/node_modules/bluebird/js/release/promise.js:729:18)
      at Promise._fulfill (/home/workspace/btc-rpc-explorer/node_modules/bluebird/js/release/promise.js:673:18)
      at Promise._resolveCallback (/home/workspace/btc-rpc-explorer/node_modules/bluebird/js/release/promise.js:466:57)
      at Promise._settlePromiseFromHandler (/home/workspace/btc-rpc-explorer/node_modules/bluebird/js/release/promise.js:559:17)
      at Promise._settlePromise (/home/workspace/btc-rpc-explorer/node_modules/bluebird/js/release/promise.js:604:18)
      at Promise._settlePromise0 (/home/workspace/btc-rpc-explorer/node_modules/bluebird/js/release/promise.js:649:10)
      at Promise._settlePromises (/home/workspace/btc-rpc-explorer/node_modules/bluebird/js/release/promise.js:729:18)
      at Promise._fulfill (/home/workspace/btc-rpc-explorer/node_modules/bluebird/js/release/promise.js:673:18)
      at Request._callback (/home/workspace/btc-rpc-explorer/node_modules/bluebird/js/release/nodeback.js:45:21)
      at Request.self.callback (/home/workspace/btc-rpc-explorer/node_modules/request/request.js:185:22)
      at Request.emit (events.js:203:15)
    userData: { error: null, request: [Object], result: [Array] } } } reason: { Error: RpcError: type=errorResponse-03
    at Client.<anonymous> (/home/workspace/btc-rpc-explorer/app/api/rpcApi.js:420:14)
    at Client.tryCatcher (/home/workspace/btc-rpc-explorer/node_modules/bluebird/js/release/util.js:16:23)
    at Promise.successAdapter (/home/workspace/btc-rpc-explorer/node_modules/bluebird/js/release/nodeify.js:23:30)
    at Promise._settlePromise (/home/workspace/btc-rpc-explorer/node_modules/bluebird/js/release/promise.js:601:21)
    at Promise._settlePromise0 (/home/workspace/btc-rpc-explorer/node_modules/bluebird/js/release/promise.js:649:10)
    at Promise._settlePromises (/home/workspace/btc-rpc-explorer/node_modules/bluebird/js/release/promise.js:729:18)
    at Promise._fulfill (/home/workspace/btc-rpc-explorer/node_modules/bluebird/js/release/promise.js:673:18)
    at Promise._resolveCallback (/home/workspace/btc-rpc-explorer/node_modules/bluebird/js/release/promise.js:466:57)
    at Promise._settlePromiseFromHandler (/home/workspace/btc-rpc-explorer/node_modules/bluebird/js/release/promise.js:559:17)
    at Promise._settlePromise (/home/workspace/btc-rpc-explorer/node_modules/bluebird/js/release/promise.js:604:18)
    at Promise._settlePromise0 (/home/workspace/btc-rpc-explorer/node_modules/bluebird/js/release/promise.js:649:10)
    at Promise._settlePromises (/home/workspace/btc-rpc-explorer/node_modules/bluebird/js/release/promise.js:729:18)
    at Promise._fulfill (/home/workspace/btc-rpc-explorer/node_modules/bluebird/js/release/promise.js:673:18)
    at Request._callback (/home/workspace/btc-rpc-explorer/node_modules/bluebird/js/release/nodeback.js:45:21)
    at Request.self.callback (/home/workspace/btc-rpc-explorer/node_modules/request/request.js:185:22)
    at Request.emit (events.js:203:15)
  userData:
   { error: null,
     request: { method: 'getblockstats', parameters: [Array] },
     result: [ [RpcError] ] } } stack: Error: RpcError: type=errorResponse-03
    at Client.<anonymous> (/home/workspace/btc-rpc-explorer/app/api/rpcApi.js:420:14)
    at Client.tryCatcher (/home/workspace/btc-rpc-explorer/node_modules/bluebird/js/release/util.js:16:23)
    at Promise.successAdapter (/home/workspace/btc-rpc-explorer/node_modules/bluebird/js/release/nodeify.js:23:30)
    at Promise._settlePromise (/home/workspace/btc-rpc-explorer/node_modules/bluebird/js/release/promise.js:601:21)
    at Promise._settlePromise0 (/home/workspace/btc-rpc-explorer/node_modules/bluebird/js/release/promise.js:649:10)
    at Promise._settlePromises (/home/workspace/btc-rpc-explorer/node_modules/bluebird/js/release/promise.js:729:18)
    at Promise._fulfill (/home/workspace/btc-rpc-explorer/node_modules/bluebird/js/release/promise.js:673:18)
    at Promise._resolveCallback (/home/workspace/btc-rpc-explorer/node_modules/bluebird/js/release/promise.js:466:57)
    at Promise._settlePromiseFromHandler (/home/workspace/btc-rpc-explorer/node_modules/bluebird/js/release/promise.js:559:17)
    at Promise._settlePromise (/home/workspace/btc-rpc-explorer/node_modules/bluebird/js/release/promise.js:604:18)
    at Promise._settlePromise0 (/home/workspace/btc-rpc-explorer/node_modules/bluebird/js/release/promise.js:649:10)
    at Promise._settlePromises (/home/workspace/btc-rpc-explorer/node_modules/bluebird/js/release/promise.js:729:18)
    at Promise._fulfill (/home/workspace/btc-rpc-explorer/node_modules/bluebird/js/release/promise.js:673:18)
    at Request._callback (/home/workspace/btc-rpc-explorer/node_modules/bluebird/js/release/nodeback.js:45:21)
    at Request.self.callback (/home/workspace/btc-rpc-explorer/node_modules/request/request.js:185:22)
    at Request.emit (events.js:203:15) +29ms
  btcexp:error Error 283h7ewsede: Error: RpcError: type=errorResponse-03, json: {"userData":{"error":null,"request":{"method":"getblockstats","parameters":[-2]},"result":[{"message":"Target block height -2 is negative","code":-8,"name":"RpcError"}]}}, userData: [object Object] (json: {"error":null,"request":{"method":"getblockstats","parameters":[-2]},"result":[{"message":"Target block height -2 is negative","code":-8,"name":"RpcError"}]}) +16ms
  btcexp:error Error 283h7ewsede: Error: RpcError: type=errorResponse-03, json: {"userData":{"error":null,"request":{"method":"getblockstats","parameters":[-3]},"result":[{"message":"Target block height -3 is negative","code":-8,"name":"RpcError"}]}}, userData: [object Object] (json: {"error":null,"request":{"method":"getblockstats","parameters":[-3]},"result":[{"message":"Target block height -3 is negative","code":-8,"name":"RpcError"}]}) +3ms
```

**Comment by janoside** [comment]
@knkrth Was this in regtest environment?

**Comment by knkrth** [comment]
@janoside No, Its on the mainnet.

**Comment by janoside** [comment]
@knkrth Are you still seeing this issue using the latest code?

**Comment by knkrth** [comment]
@janoside I'm sorry, I didn't test the latest master. I kept this issue open because someone else may have the same issue.

I'm closing this issue for now, If anyone has similar issues they can reopen this issue later.

**Comment by widecoin-project** [comment]
what is solution for this issue ?

**Comment by odomdev** [comment]
what is solution for this issue ?
