### ISSUE TITLE
Cannot read property '1' of undefined

### ISSUE THREAD

**Issue by schildbach** [janoside/btc-rpc-explorer#208]
I currently keep seeing below error message. btc-rpc-explorer 2.0.0, bitcoind 0.19.1, electrumx 1.14.0

```
Error

/workspace/views/includes/index-network-summary.pug:72
    70| 						if (false)
    71| 							small.ml-1 (1/h/d/w)
  > 72| 					td.text-right.text-monospace #{smartFeeEstimates[1]}
    73| 						small.d-md-none  
    74| 						small.text-muted /
    75| 						span #{smartFeeEstimates[6]}

Cannot read property '1' of undefined

TypeError: /workspace/views/includes/index-network-summary.pug:72
    70| 						if (false)
    71| 							small.ml-1 (1/h/d/w)
  > 72| 					td.text-right.text-monospace #{smartFeeEstimates[1]}
    73| 						small.d-md-none  
    74| 						small.text-muted /
    75| 						span #{smartFeeEstimates[6]}

Cannot read property '1' of undefined
    at eval (eval at wrap (/workspace/node_modules/pug-runtime/wrap.js:6:10), <anonymous>:1055:74)
    at template (eval at wrap (/workspace/node_modules/pug-runtime/wrap.js:6:10), <anonymous>:6049:72)
    at Object.exports.renderFile (/workspace/node_modules/pug/lib/index.js:427:38)
    at Object.exports.renderFile (/workspace/node_modules/pug/lib/index.js:417:21)
    at exports.__express (/workspace/node_modules/pug/lib/index.js:464:11)
    at View.app.engine (/workspace/app.js:68:23)
    at View.render (/workspace/node_modules/express/lib/view.js:135:8)
    at tryRender (/workspace/node_modules/express/lib/application.js:640:10)
    at Function.render (/workspace/node_modules/express/lib/application.js:592:3)
    at ServerResponse.render (/workspace/node_modules/express/lib/response.js:1012:7)
    at /workspace/routes/baseActionsRouter.js:194:9
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7)
```

**Comment by janoside** [comment]
@schildbach Added some armor to address part of this. Seems that you don't have fee estimates being returned on the homepage, but unsure why that is. Are you still seeing this?

**Comment by schildbach** [comment]
Currently it's working. I think fee estimates are not guaranteed to be available, because it needs some history.

**Comment by janoside** [comment]
Good point. Thanks for that insight. With that in mind, I'm closing this since I believe the "armor" is actually the appropriate fix for that situation ("fee estimates unavailable due to lack of history").

**Comment by schildbach** [comment]
Thanks!
