### ISSUE TITLE
getblockstats ESOCKETTIMEDOUT errors

### ISSUE THREAD

**Issue by d3spwn** [janoside/btc-rpc-explorer#220]
version 2.0.1

Whenever I go to the block-stats page, it loads 15 blocks and then stops. If I reload the page, it loads 15 more blocks.

The log contains this error:

```
Jun 20 16:30:39 debian npm[20269]: 2020-06-20T14:30:39.376Z btcexp:error Error 283h7ewsede: Error: RpcError: type=failure-02, json: {"userData":{"error":{"cause":{"code":"ESOCKETTIMEDOUT","connect":false},"isOperational":true,"code":"ESOCKETTIMEDOUT","connect":false},"request":{"method":"getblockstats","parameters":[635556]}}}, userData: [object Object] (json: {"error":{"cause":{"code":"ESOCKETTIMEDOUT","connect":false},"isOperational":true,"code":"ESOCKETTIMEDOUT","connect":false},"request":{"method":"getblockstats","parameters":[635556]}})
Jun 20 16:30:39 debian npm[20269]: 2020-06-20T14:30:39.376Z btcexp:app Unhandled Rejection at: Promise Promise {
Jun 20 16:30:39 debian npm[20269]:   <rejected> { Error: RpcError: type=failure-02
Jun 20 16:30:39 debian npm[20269]:       at Client.<anonymous> (/home/btc-rpc-explorer/btc-rpc-explorer/app/api/rpcApi.js:411:13)
Jun 20 16:30:39 debian npm[20269]:       at Client.tryCatcher (/home/btc-rpc-explorer/btc-rpc-explorer/node_modules/bluebird/js/release/util.js:16:23)
Jun 20 16:30:39 debian npm[20269]:       at Promise.errorAdapter (/home/btc-rpc-explorer/btc-rpc-explorer/node_modules/bluebird/js/release/nodeify.js:35:34)
Jun 20 16:30:39 debian npm[20269]:       at Promise._settlePromise (/home/btc-rpc-explorer/btc-rpc-explorer/node_modules/bluebird/js/release/promise.js:601:21)
Jun 20 16:30:39 debian npm[20269]:       at Promise._settlePromise0 (/home/btc-rpc-explorer/btc-rpc-explorer/node_modules/bluebird/js/release/promise.js:649:10)
Jun 20 16:30:39 debian npm[20269]:       at Promise._settlePromises (/home/btc-rpc-explorer/btc-rpc-explorer/node_modules/bluebird/js/release/promise.js:725:18)
Jun 20 16:30:39 debian npm[20269]:       at _drainQueueStep (/home/btc-rpc-explorer/btc-rpc-explorer/node_modules/bluebird/js/release/async.js:93:12)
Jun 20 16:30:39 debian npm[20269]:       at _drainQueue (/home/btc-rpc-explorer/btc-rpc-explorer/node_modules/bluebird/js/release/async.js:86:9)
Jun 20 16:30:39 debian npm[20269]:       at Async._drainQueues (/home/btc-rpc-explorer/btc-rpc-explorer/node_modules/bluebird/js/release/async.js:102:5)
Jun 20 16:30:39 debian npm[20269]:       at Immediate.Async.drainQueues [as _onImmediate] (/home/btc-rpc-explorer/btc-rpc-explorer/node_modules/bluebird/js/release/async.js:15:14)
Jun 20 16:30:39 debian npm[20269]:       at runCallback (timers.js:705:18)
Jun 20 16:30:39 debian npm[20269]:       at tryOnImmediate (timers.js:676:5)
Jun 20 16:30:39 debian npm[20269]:       at processImmediate (timers.js:658:5)
Jun 20 16:30:39 debian npm[20269]:     userData:
Jun 20 16:30:39 debian npm[20269]:      { error: [OperationalError],
Jun 20 16:30:39 debian npm[20269]:        request: [Object],
Jun 20 16:30:39 debian npm[20269]:        result: undefined } } } reason: { Error: RpcError: type=failure-02
Jun 20 16:30:39 debian npm[20269]:     at Client.<anonymous> (/home/btc-rpc-explorer/btc-rpc-explorer/app/api/rpcApi.js:411:13)
Jun 20 16:30:39 debian npm[20269]:     at Client.tryCatcher (/home/btc-rpc-explorer/btc-rpc-explorer/node_modules/bluebird/js/release/util.js:16:23)
Jun 20 16:30:39 debian npm[20269]:     at Promise.errorAdapter (/home/btc-rpc-explorer/btc-rpc-explorer/node_modules/bluebird/js/release/nodeify.js:35:34)
Jun 20 16:30:39 debian npm[20269]:     at Promise._settlePromise (/home/btc-rpc-explorer/btc-rpc-explorer/node_modules/bluebird/js/release/promise.js:601:21)
Jun 20 16:30:39 debian npm[20269]:     at Promise._settlePromise0 (/home/btc-rpc-explorer/btc-rpc-explorer/node_modules/bluebird/js/release/promise.js:649:10)
Jun 20 16:30:39 debian npm[20269]:     at Promise._settlePromises (/home/btc-rpc-explorer/btc-rpc-explorer/node_modules/bluebird/js/release/promise.js:725:18)
Jun 20 16:30:39 debian npm[20269]:     at _drainQueueStep (/home/btc-rpc-explorer/btc-rpc-explorer/node_modules/bluebird/js/release/async.js:93:12)
Jun 20 16:30:39 debian npm[20269]:     at _drainQueue (/home/btc-rpc-explorer/btc-rpc-explorer/node_modules/bluebird/js/release/async.js:86:9)
Jun 20 16:30:39 debian npm[20269]:     at Async._drainQueues (/home/btc-rpc-explorer/btc-rpc-explorer/node_modules/bluebird/js/release/async.js:102:5)
Jun 20 16:30:39 debian npm[20269]:     at Immediate.Async.drainQueues [as _onImmediate] (/home/btc-rpc-explorer/btc-rpc-explorer/node_modules/bluebird/js/release/async.js:15:14)
Jun 20 16:30:39 debian npm[20269]:     at runCallback (timers.js:705:18)
Jun 20 16:30:39 debian npm[20269]:     at tryOnImmediate (timers.js:676:5)
Jun 20 16:30:39 debian npm[20269]:     at processImmediate (timers.js:658:5)
Jun 20 16:30:39 debian npm[20269]:   userData:
Jun 20 16:30:39 debian npm[20269]:    { error:
Jun 20 16:30:39 debian npm[20269]:       { Error: ESOCKETTIMEDOUT
Jun 20 16:30:39 debian npm[20269]:           at ClientRequest.<anonymous> (/home/btc-rpc-explorer/btc-rpc-explorer/node_modules/request/request.js:816:19)
Jun 20 16:30:39 debian npm[20269]:           at Object.onceWrapper (events.js:286:20)
Jun 20 16:30:39 debian npm[20269]:           at ClientRequest.emit (events.js:198:13)
Jun 20 16:30:39 debian npm[20269]:           at Socket.emitRequestTimeout (_http_client.js:673:40)
Jun 20 16:30:39 debian npm[20269]:           at Object.onceWrapper (events.js:286:20)
Jun 20 16:30:39 debian npm[20269]:           at Socket.emit (events.js:198:13)
Jun 20 16:30:39 debian npm[20269]:           at Socket._onTimeout (net.js:443:8)
Jun 20 16:30:39 debian npm[20269]:           at ontimeout (timers.js:436:11)
Jun 20 16:30:39 debian npm[20269]:           at tryOnTimeout (timers.js:300:5)
Jun 20 16:30:39 debian npm[20269]:           at listOnTimeout (timers.js:263:5)
Jun 20 16:30:39 debian npm[20269]:           at Timer.processTimers (timers.js:223:10)
Jun 20 16:30:39 debian npm[20269]:         cause: [Error],
Jun 20 16:30:39 debian npm[20269]:         isOperational: true,
Jun 20 16:30:39 debian npm[20269]:         code: 'ESOCKETTIMEDOUT',
Jun 20 16:30:39 debian npm[20269]:         connect: false },
Jun 20 16:30:39 debian npm[20269]:      request: { method: 'getblockstats', parameters: [Array] },
Jun 20 16:30:39 debian npm[20269]:      result: undefined } } stack: Error: RpcError: type=failure-02
Jun 20 16:30:39 debian npm[20269]:     at Client.<anonymous> (/home/btc-rpc-explorer/btc-rpc-explorer/app/api/rpcApi.js:411:13)
Jun 20 16:30:39 debian npm[20269]:     at Client.tryCatcher (/home/btc-rpc-explorer/btc-rpc-explorer/node_modules/bluebird/js/release/util.js:16:23)
Jun 20 16:30:39 debian npm[20269]:     at Promise.errorAdapter (/home/btc-rpc-explorer/btc-rpc-explorer/node_modules/bluebird/js/release/nodeify.js:35:34)
Jun 20 16:30:39 debian npm[20269]:     at Promise._settlePromise (/home/btc-rpc-explorer/btc-rpc-explorer/node_modules/bluebird/js/release/promise.js:601:21)
Jun 20 16:30:39 debian npm[20269]:     at Promise._settlePromise0 (/home/btc-rpc-explorer/btc-rpc-explorer/node_modules/bluebird/js/release/promise.js:649:10)
Jun 20 16:30:39 debian npm[20269]:     at Promise._settlePromises (/home/btc-rpc-explorer/btc-rpc-explorer/node_modules/bluebird/js/release/promise.js:725:18)
Jun 20 16:30:39 debian npm[20269]:     at _drainQueueStep (/home/btc-rpc-explorer/btc-rpc-explorer/node_modules/bluebird/js/release/async.js:93:12)
Jun 20 16:30:39 debian npm[20269]:     at _drainQueue (/home/btc-rpc-explorer/btc-rpc-explorer/node_modules/bluebird/js/release/async.js:86:9)
Jun 20 16:30:39 debian npm[20269]:     at Async._drainQueues (/home/btc-rpc-explorer/btc-rpc-explorer/node_modules/bluebird/js/release/async.js:102:5)
Jun 20 16:30:39 debian npm[20269]:     at Immediate.Async.drainQueues [as _onImmediate] (/home/btc-rpc-explorer/btc-rpc-explorer/node_modules/bluebird/js/release/async.js:15:14)
Jun 20 16:30:39 debian npm[20269]:     at runCallback (timers.js:705:18)
Jun 20 16:30:39 debian npm[20269]:     at tryOnImmediate (timers.js:676:5)
Jun 20 16:30:39 debian npm[20269]:     at processImmediate (timers.js:658:5)
```

**Comment by janoside** [comment]
Not sure about this, but I wonder if your node is just getting overloaded. Are you running on low-powered hardware? If so, you might want to check out this configuration setting: [BTCEXP_RPC_CONCURRENCY](https://github.com/janoside/btc-rpc-explorer/blob/master/.env-sample#L42). If you set a lower value than the default (10) then btc-rpc-explorer will send fewer concurrent requests to your node. Can you try that out and let me know?

**Comment by d3spwn** [comment]
I've reduced it to 1 and now I only occasionally get the error. What would be the minimum requirements for this feature? I'm running my node on an Intel i3 2.4Ghz with 16GB memory.

**Comment by janoside** [comment]
It's a tricky issue. There's not really any "right" value except that, as the config description indicates, you want the value to be no greater than the `rpcworkqueue` value of your node. I believe the default for `rpcworkqueue` is/was 16, but I don't know if that's still the default in bitcoind or if you're even using the default. At the root, this issue is not something that btc-rpc-explorer can "get around" - it's basically your node saying I'm rejecting your request. A value of 1 is, of course, the "safest" value, but it's likely to be unnecessarily conservative and if you're still seeing these connection-reset errors you'll likely want to dive deeper into what your node is doing.

I'm closing this for now, but feel free to comment here with more questions or if your investigations reveal any more relevant info.

**Comment by mtaylor769** [comment]
I'm also getting this error. 
`btcexp:error Error 283h7ewsede: Error: RpcError: type=failure-02, json: {"userData":{"error":{"cause":{"code":"ESOCKETTIMEDOUT","connect":false},"isOperational":true,"code":"ESOCKETTIMEDOUT","connect":false},"request":{"method":"getblockstats","parameters":[165324]}}}, userData: [object Object] (json: {"error":{"cause":{"code":"ESOCKETTIMEDOUT","connect":false},"isOperational":true,"code":"ESOCKETTIMEDOUT","connect":false},"request":{"method":"getblockstats","parameters":[165324]}}) +5s
`

I'm running bitcoincore0.20.0 on a RaspberryPi4 running the 64bit beta OS (aarch64)
`uname -a
Linux btcminer 5.4.51-v8+ #1327 SMP PREEMPT Thu Jul 23 11:11:34 BST 2020 aarch64 GNU/Linux`
I have the ~/.config/btc-rpc-explorer.env file from the example and only changed my `rpcuser` and `rpcpassword` values, as well as the recommended `BTCEXP_RPC_CONCURRENCY=1` setting described above (which prevented it from crashing altogether)
Any insight is appreciated.
