### ISSUE TITLE
RpcError: ESOCKETTIMEDOUT

### ISSUE THREAD

**Issue by mtaylor769** [janoside/btc-rpc-explorer#231]
I'm also getting this error. (This may be a duplicate of CLOSED #220 , but is happening today)
`btcexp:error Error 283h7ewsede: Error: RpcError: type=failure-02, json: {"userData":{"error":{"cause":{"code":"ESOCKETTIMEDOUT","connect":false},"isOperational":true,"code":"ESOCKETTIMEDOUT","connect":false},"request":{"method":"getblockstats","parameters":[165324]}}}, userData: [object Object] (json: {"error":{"cause":{"code":"ESOCKETTIMEDOUT","connect":false},"isOperational":true,"code":"ESOCKETTIMEDOUT","connect":false},"request":{"method":"getblockstats","parameters":[165324]}}) +5s`

I'm running bitcoincore0.20.0 on a RaspberryPi4 running the 64bit beta OS (aarch64)
`uname -a 
Linux btcminer 5.4.51-v8+ #1327 SMP PREEMPT Thu Jul 23 11:11:34 BST 2020 aarch64 GNU/Linux`

I have the ~/.config/btc-rpc-explorer.env file from the example and only changed my `rpcuser` and `rpcpassword` values, as well as the recommended `BTCEXP_RPC_CONCURRENCY=1` setting described in #220  (which prevented it from crashing altogether)
Any insight is appreciated.

**Comment by mtaylor769** [comment]
Some more error info:
`
btcexp:error Error 283h7ewsede: Error: RpcError: type=failure-02, json: {"userData":{"error":{"cause":{"code":"ESOCKETTIMEDOUT","connect":false},"isOperational":true,"code":"ESOCKETTIMEDOUT","connect":false},"request":{"method":"getblockstats","parameters":[171567]}}}, userData: [object Object] (json: {"error":{"cause":{"code":"ESOCKETTIMEDOUT","connect":false},"isOperational":true,"code":"ESOCKETTIMEDOUT","connect":false},"request":{"method":"getblockstats","parameters":[171567]}}) +2m
  btcexp:app Unhandled Rejection at: Promise Promise {
  <rejected> { Error: RpcError: type=failure-02
      at Client.<anonymous> (/home/pi/.nvm/versions/node/v10.22.0/lib/node_modules/btc-rpc-explorer/app/api/rpcApi.js:411:13)
      at Client.tryCatcher (/home/pi/.nvm/versions/node/v10.22.0/lib/node_modules/btc-rpc-explorer/node_modules/bluebird/js/release/util.js:16:23)
      at Promise.errorAdapter (/home/pi/.nvm/versions/node/v10.22.0/lib/node_modules/btc-rpc-explorer/node_modules/bluebird/js/release/nodeify.js:35:34)
      at Promise._settlePromise (/home/pi/.nvm/versions/node/v10.22.0/lib/node_modules/btc-rpc-explorer/node_modules/bluebird/js/release/promise.js:601:21)
      at Promise._settlePromise0 (/home/pi/.nvm/versions/node/v10.22.0/lib/node_modules/btc-rpc-explorer/node_modules/bluebird/js/release/promise.js:649:10)
      at Promise._settlePromises (/home/pi/.nvm/versions/node/v10.22.0/lib/node_modules/btc-rpc-explorer/node_modules/bluebird/js/release/promise.js:725:18)
      at _drainQueueStep (/home/pi/.nvm/versions/node/v10.22.0/lib/node_modules/btc-rpc-explorer/node_modules/bluebird/js/release/async.js:93:12)
      at _drainQueue (/home/pi/.nvm/versions/node/v10.22.0/lib/node_modules/btc-rpc-explorer/node_modules/bluebird/js/release/async.js:86:9)
      at Async._drainQueues (/home/pi/.nvm/versions/node/v10.22.0/lib/node_modules/btc-rpc-explorer/node_modules/bluebird/js/release/async.js:102:5)
      at Immediate.Async.drainQueues [as _onImmediate] (/home/pi/.nvm/versions/node/v10.22.0/lib/node_modules/btc-rpc-explorer/node_modules/bluebird/js/release/async.js:15:14)
      at runCallback (timers.js:705:18)
      at tryOnImmediate (timers.js:676:5)
      at processImmediate (timers.js:658:5)
    userData:
     { error: [OperationalError],
       request: [Object],
       result: undefined } } } reason: { Error: RpcError: type=failure-02
    at Client.<anonymous> (/home/pi/.nvm/versions/node/v10.22.0/lib/node_modules/btc-rpc-explorer/app/api/rpcApi.js:411:13)
    at Client.tryCatcher (/home/pi/.nvm/versions/node/v10.22.0/lib/node_modules/btc-rpc-explorer/node_modules/bluebird/js/release/util.js:16:23)
    at Promise.errorAdapter (/home/pi/.nvm/versions/node/v10.22.0/lib/node_modules/btc-rpc-explorer/node_modules/bluebird/js/release/nodeify.js:35:34)
    at Promise._settlePromise (/home/pi/.nvm/versions/node/v10.22.0/lib/node_modules/btc-rpc-explorer/node_modules/bluebird/js/release/promise.js:601:21)
    at Promise._settlePromise0 (/home/pi/.nvm/versions/node/v10.22.0/lib/node_modules/btc-rpc-explorer/node_modules/bluebird/js/release/promise.js:649:10)
    at Promise._settlePromises (/home/pi/.nvm/versions/node/v10.22.0/lib/node_modules/btc-rpc-explorer/node_modules/bluebird/js/release/promise.js:725:18)
    at _drainQueueStep (/home/pi/.nvm/versions/node/v10.22.0/lib/node_modules/btc-rpc-explorer/node_modules/bluebird/js/release/async.js:93:12)
    at _drainQueue (/home/pi/.nvm/versions/node/v10.22.0/lib/node_modules/btc-rpc-explorer/node_modules/bluebird/js/release/async.js:86:9)
    at Async._drainQueues (/home/pi/.nvm/versions/node/v10.22.0/lib/node_modules/btc-rpc-explorer/node_modules/bluebird/js/release/async.js:102:5)
    at Immediate.Async.drainQueues [as _onImmediate] (/home/pi/.nvm/versions/node/v10.22.0/lib/node_modules/btc-rpc-explorer/node_modules/bluebird/js/release/async.js:15:14)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)
  userData:
   { error:
      { Error: ESOCKETTIMEDOUT
          at ClientRequest.<anonymous> (/home/pi/.nvm/versions/node/v10.22.0/lib/node_modules/btc-rpc-explorer/node_modules/request/request.js:816:19)
          at Object.onceWrapper (events.js:286:20)
          at ClientRequest.emit (events.js:198:13)
          at Socket.emitRequestTimeout (_http_client.js:673:40)
          at Object.onceWrapper (events.js:286:20)
          at Socket.emit (events.js:198:13)
          at Socket._onTimeout (net.js:443:8)
          at ontimeout (timers.js:436:11)
          at tryOnTimeout (timers.js:300:5)
          at listOnTimeout (timers.js:263:5)
          at Timer.processTimers (timers.js:223:10)
        cause: [Error],
        isOperational: true,
        code: 'ESOCKETTIMEDOUT',
        connect: false },
     request: { method: 'getblockstats', parameters: [Array] },
     result: undefined } } stack: Error: RpcError: type=failure-02
    at Client.<anonymous> (/home/pi/.nvm/versions/node/v10.22.0/lib/node_modules/btc-rpc-explorer/app/api/rpcApi.js:411:13)
    at Client.tryCatcher (/home/pi/.nvm/versions/node/v10.22.0/lib/node_modules/btc-rpc-explorer/node_modules/bluebird/js/release/util.js:16:23)
    at Promise.errorAdapter (/home/pi/.nvm/versions/node/v10.22.0/lib/node_modules/btc-rpc-explorer/node_modules/bluebird/js/release/nodeify.js:35:34)
    at Promise._settlePromise (/home/pi/.nvm/versions/node/v10.22.0/lib/node_modules/btc-rpc-explorer/node_modules/bluebird/js/release/promise.js:601:21)
    at Promise._settlePromise0 (/home/pi/.nvm/versions/node/v10.22.0/lib/node_modules/btc-rpc-explorer/node_modules/bluebird/js/release/promise.js:649:10)
    at Promise._settlePromises (/home/pi/.nvm/versions/node/v10.22.0/lib/node_modules/btc-rpc-explorer/node_modules/bluebird/js/release/promise.js:725:18)
    at _drainQueueStep (/home/pi/.nvm/versions/node/v10.22.0/lib/node_modules/btc-rpc-explorer/node_modules/bluebird/js/release/async.js:93:12)
    at _drainQueue (/home/pi/.nvm/versions/node/v10.22.0/lib/node_modules/btc-rpc-explorer/node_modules/bluebird/js/release/async.js:86:9)
    at Async._drainQueues (/home/pi/.nvm/versions/node/v10.22.0/lib/node_modules/btc-rpc-explorer/node_modules/bluebird/js/release/async.js:102:5)
    at Immediate.Async.drainQueues [as _onImmediate] (/home/pi/.nvm/versions/node/v10.22.0/lib/node_modules/btc-rpc-explorer/node_modules/bluebird/js/release/async.js:15:14)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5) +7s
`

**Comment by pouyiouk** [comment]
I had the same issue and I was able to solve it. Are you running the client using bitcoind? Let it synchronise completely/until you get and have the message synchronised with the network. So each new transaction can be automatically added to chain according to the network updates.

**Comment by janoside** [comment]
@mtaylor769 I'm closing stale issues, but if you are continuing to have trouble I'd be happy to know if you tried pouyiouk's suggestions and/or dig in deeper if needed.

**Comment by Abbeville** [comment]
> I had the same issue and I was able to solve it. Are you running the client using bitcoind? Let it synchronise completely/until you get and have the message synchronised with the network. So each new transaction can be automatically added to chain according to the network updates.

I have the same problem. But i can only run bitcoind on the server. I can't run bitcoinq from SSH. What do you suggest i do please?
