### ISSUE TITLE
`invalid csrf token` [v2.0.0]

### ISSUE THREAD

**Issue by shawnyeager** [janoside/btc-rpc-explorer#233]
Using the installer script triggered from [raspiblitz's](https://github.com/rootzoll/raspiblitz) menu [v1.6.0], I'm seeing the following each time I search for a transaction:

## Error

`invalid csrf token`

### 403

```
ForbiddenError: invalid csrf token
    at csrf (/home/btcrpcexplorer/btc-rpc-explorer/node_modules/csurf/index.js:112:19)
    at Layer.handle [as handle_request] (/home/btcrpcexplorer/btc-rpc-explorer/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/home/btcrpcexplorer/btc-rpc-explorer/node_modules/express/lib/router/index.js:317:13)
    at /home/btcrpcexplorer/btc-rpc-explorer/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/home/btcrpcexplorer/btc-rpc-explorer/node_modules/express/lib/router/index.js:335:12)
    at next (/home/btcrpcexplorer/btc-rpc-explorer/node_modules/express/lib/router/index.js:275:10)
    at /home/btcrpcexplorer/btc-rpc-explorer/app.js:586:2
    at Layer.handle [as handle_request] (/home/btcrpcexplorer/btc-rpc-explorer/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/home/btcrpcexplorer/btc-rpc-explorer/node_modules/express/lib/router/index.js:317:13)
    at /home/btcrpcexplorer/btc-rpc-explorer/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/home/btcrpcexplorer/btc-rpc-explorer/node_modules/express/lib/router/index.js:335:12)
    at next (/home/btcrpcexplorer/btc-rpc-explorer/node_modules/express/lib/router/index.js:275:10)
    at /home/btcrpcexplorer/btc-rpc-explorer/app.js:469:2
    at Layer.handle [as handle_request] (/home/btcrpcexplorer/btc-rpc-explorer/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/home/btcrpcexplorer/btc-rpc-explorer/node_modules/express/lib/router/index.js:317:13)
    at /home/btcrpcexplorer/btc-rpc-explorer/node_modules/express/lib/router/index.js:284:7
```

**Comment by openoms** [comment]
This happens to me when leaving the site open for a while, but a page refresh solves it every time.

**Comment by shawnyeager** [comment]
@openoms Correct, you are. Just tried again in a "fresh" tab.
