### ISSUE TITLE
Work queue depth exceeded / SyntaxError: Unexpected token W in JSON at position 0

### ISSUE THREAD

**Issue by schildbach** [janoside/btc-rpc-explorer#237]
I'm using the Docker image, current version 2.0.2. Connected to bitcoind 0.20.1 and ElectrumX 1.15.0.

Because I discovered btc-rpc-explorer is using much RAM and CPU without actually being used, I recently limited RAM usage to 512 MB.

It doesn't take long until the container exits with this error in the log and exit code 1:

```
btc-rpc-explorer_1  | 2020-09-26T17:08:35.481Z btcexp:error Error 32ugegdfsde: Error: RpcError: type=failure-01, json: {"userData":{"error":{"cause":{"code":"ESOCKETTIMEDOUT","connect":false},"isOperational":true,"code":"ESOCKETTIMEDOUT","connect":false},"request":"getnetworkinfo"}}
btc-rpc-explorer_1  | 2020-09-26T17:08:40.966Z btcexp:error Error 937gf47dsyde: Error: connect ECONNREFUSED 172.21.0.4:50001, json: {"errno":"ECONNREFUSED","code":"ECONNREFUSED","syscall":"connect","address":"172.21.0.4","port":50001}, userData: [object Object] (json: {"host":"electrumx","port":50001,"protocol":"tcp"})
btc-rpc-explorer_1  | 2020-09-26T17:08:40.967Z btcexp:error Error 937gf47dsyde: Error: connect ECONNREFUSED 172.21.0.4:50001, json: {"errno":"ECONNREFUSED","code":"ECONNREFUSED","syscall":"connect","address":"172.21.0.4","port":50001}, userData: [object Object] (json: {"host":"electrumx","port":50001,"protocol":"tcp"})
btc-rpc-explorer_1  | 2020-09-26T17:08:50.971Z btcexp:error Error 937gf47dsyde: Error: connect ECONNREFUSED 172.21.0.4:50001, json: {"errno":"ECONNREFUSED","code":"ECONNREFUSED","syscall":"connect","address":"172.21.0.4","port":50001}, userData: [object Object] (json: {"host":"electrumx","port":50001,"protocol":"tcp"})
btc-rpc-explorer_1  | 2020-09-26T17:08:50.971Z btcexp:error Error 937gf47dsyde: Error: connect ECONNREFUSED 172.21.0.4:50001, json: {"errno":"ECONNREFUSED","code":"ECONNREFUSED","syscall":"connect","address":"172.21.0.4","port":50001}, userData: [object Object] (json: {"host":"electrumx","port":50001,"protocol":"tcp"})
btc-rpc-explorer_1  | 2020-09-26T17:09:00.474Z btcexp:app Verifying RPC connection...
btc-rpc-explorer_1  | undefined:1
btc-rpc-explorer_1  | Work queue depth exceeded
btc-rpc-explorer_1  | ^
btc-rpc-explorer_1  | 
btc-rpc-explorer_1  | SyntaxError: Unexpected token W in JSON at position 0
btc-rpc-explorer_1  |     at JSON.parse (<anonymous>)
btc-rpc-explorer_1  |     at obfuscateResponse (/workspace/node_modules/bitcoin-core/dist/src/logging/request-obfuscator.js:60:23)
btc-rpc-explorer_1  |     at obfuscate (/workspace/node_modules/bitcoin-core/dist/src/logging/request-obfuscator.js:142:3)
btc-rpc-explorer_1  |     at /workspace/node_modules/bitcoin-core/dist/src/logging/request-logger.js:24:36
btc-rpc-explorer_1  |     at Request.<anonymous> (/workspace/node_modules/@uphold/request-logger/src/index.js:33:9)
btc-rpc-explorer_1  |     at emitTwo (events.js:131:20)
btc-rpc-explorer_1  |     at Request.emit (events.js:214:7)
btc-rpc-explorer_1  |     at Request.<anonymous> (/workspace/node_modules/request/request.js:1154:10)
btc-rpc-explorer_1  |     at emitOne (events.js:116:13)
btc-rpc-explorer_1  |     at Request.emit (events.js:211:7)
btc-rpc-explorer_1  |     at IncomingMessage.<anonymous> (/workspace/node_modules/request/request.js:1076:12)
btc-rpc-explorer_1  |     at Object.onceWrapper (events.js:313:30)
btc-rpc-explorer_1  |     at emitNone (events.js:111:20)
btc-rpc-explorer_1  |     at IncomingMessage.emit (events.js:208:7)
btc-rpc-explorer_1  |     at endReadableNT (_stream_readable.js:1064:12)
btc-rpc-explorer_1  |     at _combinedTickCallback (internal/process/next_tick.js:139:11)
btc-rpc-explorer_1  | npm ERR! code ELIFECYCLE
btc-rpc-explorer_1  | npm ERR! errno 1
btc-rpc-explorer_1  | npm ERR! btc-rpc-explorer@2.0.2 start: `node ./bin/www`
btc-rpc-explorer_1  | npm ERR! Exit status 1
btc-rpc-explorer_1  | npm ERR! 
btc-rpc-explorer_1  | npm ERR! Failed at the btc-rpc-explorer@2.0.2 start script.
btc-rpc-explorer_1  | npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
btc-rpc-explorer_1  | 
btc-rpc-explorer_1  | npm ERR! A complete log of this run can be found in:
btc-rpc-explorer_1  | npm ERR!     /root/.npm/_logs/2020-09-26T17_09_00_530Z-debug.log
```

**Comment by JLSchuler99** [comment]
I am running into this issue, is there a fix?

**Comment by tradewind886** [comment]
`btcexp:app Starting BTC RPC Explorer, v2.2.0 at 127.0.0.1:3002/ +0ms
  btcexp:app Connecting to RPC node at 127.0.0.1:8332 +1ms
  btcexp:app Verifying RPC connection... +10ms
  btcexp:app Loading mining pools config +1ms
  btcexp:app RPC Connected: version=210000 subversion=/Satoshi:0.21.0/, parsedVersion(used for RPC versioning)=0.21.0, protocolversion=70016, chain=main, services=[NETWORK, WITNESS, NETWORK_LIMITED] +805ms
  btcexp:app Loading historical data for chain=main +1ms
  btcexp:error Error 283h7ewsede: Error: RpcError: type=failure-02, json: {"userData":{"error":{"cause":{"code":"ESOCKETTIMEDOUT","connect":false},"isOperational":true,"code":"ESOCKETTIMEDOUT","connect":false},"request":{"method":"getblockstats","parameters":[672948]}}}, userData: [object Object] (json: {"error":{"cause":{"code":"ESOCKETTIMEDOUT","connect":false},"isOperational":true,"code":"ESOCKETTIMEDOUT","connect":false},"request":{"method":"getblockstats","parameters":[672948]}}) +0ms
  btcexp:error Error 283h7ewsede: Error: RpcError: type=failure-02, json: {"userData":{"error":{"cause":{"code":"ESOCKETTIMEDOUT","connect":false},"isOperational":true,"code":"ESOCKETTIMEDOUT","connect":false},"request":{"method":"getblockstats","parameters":[672947]}}}, userData: [object Object] (json: {"error":{"cause":{"code":"ESOCKETTIMEDOUT","connect":false},"isOperational":true,"code":"ESOCKETTIMEDOUT","connect":false},"request":{"method":"getblockstats","parameters":[672947]}}) +1ms
  btcexp:error Error 283h7ewsede: Error: RpcError: type=failure-02, json: {"userData":{"error":{"cause":{"code":"ESOCKETTIMEDOUT","connect":false},"isOperational":true,"code":"ESOCKETTIMEDOUT","connect":false},"request":{"method":"getblockstats","parameters":[672946]}}}, userData: [object Object] (json: {"error":{"cause":{"code":"ESOCKETTIMEDOUT","connect":false},"isOperational":true,"code":"ESOCKETTIMEDOUT","connect":false},"request":{"method":"getblockstats","parameters":[672946]}}) +1ms
  btcexp:app Unhandled Rejection at: Promise Promise {
  <rejected> Error: RpcError: type=failure-02
      at Client.<anonymous> (C:\Users\Calson\AppData\Roaming\npm\node_modules\btc-rpc-explorer\app\api\rpcApi.js:411:13)
      at Client.tryCatcher (C:\Users\Calson\AppData\Roaming\npm\node_modules\btc-rpc-explorer\node_modules\bluebird\js\release\util.js:16:23)
      at Promise.errorAdapter (C:\Users\Calson\AppData\Roaming\npm\node_modules\btc-rpc-explorer\node_modules\bluebird\js\release\nodeify.js:35:34)
      at Promise._settlePromise (C:\Users\Calson\AppData\Roaming\npm\node_modules\btc-rpc-explorer\node_modules\bluebird\js\release\promise.js:601:21)
      at Promise._settlePromise0 (C:\Users\Calson\AppData\Roaming\npm\node_modules\btc-rpc-explorer\node_modules\bluebird\js\release\promise.js:649:10)
      at Promise._settlePromises (C:\Users\Calson\AppData\Roaming\npm\node_modules\btc-rpc-explorer\node_modules\bluebird\js\release\promise.js:725:18)
      at _drainQueueStep (C:\Users\Calson\AppData\Roaming\npm\node_modules\btc-rpc-explorer\node_modules\bluebird\js\release\async.js:93:12)
      at _drainQueue (C:\Users\Calson\AppData\Roaming\npm\node_modules\btc-rpc-explorer\node_modules\bluebird\js\release\async.js:86:9)
      at Async._drainQueues (C:\Users\Calson\AppData\Roaming\npm\node_modules\btc-rpc-explorer\node_modules\bluebird\js\release\async.js:102:5)
      at Immediate.Async.drainQueues [as _onImmediate] (C:\Users\Calson\AppData\Roaming\npm\node_modules\btc-rpc-explorer\node_modules\bluebird\js\release\async.js:15:14)
      at processImmediate (internal/timers.js:461:21) {
    userData: { error: [OperationalError], request: [Object], result: undefined }
  }
} reason: Error: RpcError: type=failure-02
    at Client.<anonymous> (C:\Users\Calson\AppData\Roaming\npm\node_modules\btc-rpc-explorer\app\api\rpcApi.js:411:13)
    at Client.tryCatcher (C:\Users\Calson\AppData\Roaming\npm\node_modules\btc-rpc-explorer\node_modules\bluebird\js\release\util.js:16:23)
    at Promise.errorAdapter (C:\Users\Calson\AppData\Roaming\npm\node_modules\btc-rpc-explorer\node_modules\bluebird\js\release\nodeify.js:35:34)
    at Promise._settlePromise (C:\Users\Calson\AppData\Roaming\npm\node_modules\btc-rpc-explorer\node_modules\bluebird\js\release\promise.js:601:21)
    at Promise._settlePromise0 (C:\Users\Calson\AppData\Roaming\npm\node_modules\btc-rpc-explorer\node_modules\bluebird\js\release\promise.js:649:10)
    at Promise._settlePromises (C:\Users\Calson\AppData\Roaming\npm\node_modules\btc-rpc-explorer\node_modules\bluebird\js\release\promise.js:725:18)
    at _drainQueueStep (C:\Users\Calson\AppData\Roaming\npm\node_modules\btc-rpc-explorer\node_modules\bluebird\js\release\async.js:93:12)
    at _drainQueue (C:\Users\Calson\AppData\Roaming\npm\node_modules\btc-rpc-explorer\node_modules\bluebird\js\release\async.js:86:9)
    at Async._drainQueues (C:\Users\Calson\AppData\Roaming\npm\node_modules\btc-rpc-explorer\node_modules\bluebird\js\release\async.js:102:5)
    at Immediate.Async.drainQueues [as _onImmediate] (C:\Users\Calson\AppData\Roaming\npm\node_modules\btc-rpc-explorer\node_modules\bluebird\js\release\async.js:15:14)
    at processImmediate (internal/timers.js:461:21) {
  userData: {
    error: OperationalError: ESOCKETTIMEDOUT
        at ClientRequest.<anonymous> (C:\Users\Calson\AppData\Roaming\npm\node_modules\btc-rpc-explorer\node_modules\request\request.js:816:19)
        at Object.onceWrapper (events.js:421:28)
        at ClientRequest.emit (events.js:315:20)
        at Socket.emitRequestTimeout (_http_client.js:784:9)
        at Object.onceWrapper (events.js:421:28)
        at Socket.emit (events.js:327:22)
        at Socket._onTimeout (net.js:483:8)
        at listOnTimeout (internal/timers.js:554:17)
        at processTimers (internal/timers.js:497:7) {
      cause: [Error],
      isOperational: true,
      code: 'ESOCKETTIMEDOUT',
      connect: false
    },
    request: { method: 'getblockstats', parameters: [Array] },
    result: undefined
  }
} stack: Error: RpcError: type=failure-02
    at Client.<anonymous> (C:\Users\Calson\AppData\Roaming\npm\node_modules\btc-rpc-explorer\app\api\rpcApi.js:411:13)
    at Client.tryCatcher (C:\Users\Calson\AppData\Roaming\npm\node_modules\btc-rpc-explorer\node_modules\bluebird\js\release\util.js:16:23)
    at Promise.errorAdapter (C:\Users\Calson\AppData\Roaming\npm\node_modules\btc-rpc-explorer\node_modules\bluebird\js\release\nodeify.js:35:34)
    at Promise._settlePromise (C:\Users\Calson\AppData\Roaming\npm\node_modules\btc-rpc-explorer\node_modules\bluebird\js\release\promise.js:601:21)
    at Promise._settlePromise0 (C:\Users\Calson\AppData\Roaming\npm\node_modules\btc-rpc-explorer\node_modules\bluebird\js\release\promise.js:649:10)
    at Promise._settlePromises (C:\Users\Calson\AppData\Roaming\npm\node_modules\btc-rpc-explorer\node_modules\bluebird\js\release\promise.js:725:18)
    at _drainQueueStep (C:\Users\Calson\AppData\Roaming\npm\node_modules\btc-rpc-explorer\node_modules\bluebird\js\release\async.js:93:12)
    at _drainQueue (C:\Users\Calson\AppData\Roaming\npm\node_modules\btc-rpc-explorer\node_modules\bluebird\js\release\async.js:86:9)
    at Async._drainQueues (C:\Users\Calson\AppData\Roaming\npm\node_modules\btc-rpc-explorer\node_modules\bluebird\js\release\async.js:102:5)
    at Immediate.Async.drainQueues [as _onImmediate] (C:\Users\Calson\AppData\Roaming\npm\node_modules\btc-rpc-explorer\node_modules\bluebird\js\release\async.js:15:14)
    at processImmediate (internal/timers.js:461:21) +5s
  btcexp:error Error 283h7ewsede: Error: RpcError: type=failure-02, json: {"userData":{"error":{"cause":{"code":"ESOCKETTIMEDOUT","connect":false},"isOperational":true,"code":"ESOCKETTIMEDOUT","connect":false},"request":{"method":"getblockstats","parameters":[672945]}}}, userData: [object Object] (json: {"error":{"cause":{"code":"ESOCKETTIMEDOUT","connect":false},"isOperational":true,"code":"ESOCKETTIMEDOUT","connect":false},"request":{"method":"getblockstats","parameters":[672945]}}) +305ms
  btcexp:error Error 283h7ewsede: Error: RpcError: type=failure-02, json: {"userData":{"error":{"cause":{"code":"ESOCKETTIMEDOUT","connect":false},"isOperational":true,"code":"ESOCKETTIMEDOUT","connect":false},"request":{"method":"getblockstats","parameters":[672944]}}}, userData: [object Object] (json: {"error":{"cause":{"code":"ESOCKETTIMEDOUT","connect":false},"isOperational":true,"code":"ESOCKETTIMEDOUT","connect":false},"request":{"method":"getblockstats","parameters":[672944]}}) +15ms
  btcexp:error Error 283h7ewsede: Error: RpcError: type=failure-02, json: {"userData":{"error":{"cause":{"code":"ESOCKETTIMEDOUT","connect":false},"isOperational":true,"code":"ESOCKETTIMEDOUT","connect":false},"request":{"method":"getblockstats","parameters":[672943]}}}, userData: [object Object] (json: {"error":{"cause":{"code":"ESOCKETTIMEDOUT","connect":false},"isOperational":true,"code":"ESOCKETTIMEDOUT","connect":false},"request":{"method":"getblockstats","parameters":[672943]}}) +15ms
  btcexp:error Error 283h7ewsede: Error: RpcError: type=failure-02, json: {"userData":{"error":{"cause":{"code":"ESOCKETTIMEDOUT","connect":false},"isOperational":true,"code":"ESOCKETTIMEDOUT","connect":false},"request":{"method":"getblockstats","parameters":[672942]}}}, userData: [object Object] (json: {"error":{"cause":{"code":"ESOCKETTIMEDOUT","connect":false},"isOperational":true,"code":"ESOCKETTIMEDOUT","connect":false},"request":{"method":"getblockstats","parameters":[672942]}}) +2s
  btcexp:error Error 283h7ewsede: Error: RpcError: type=failure-02, json: {"userData":{"error":{"cause":{"code":"ESOCKETTIMEDOUT","connect":false},"isOperational":true,"code":"ESOCKETTIMEDOUT","connect":false},"request":{"method":"getblockstats","parameters":[672941]}}}, userData: [object Object] (json: {"error":{"cause":{"code":"ESOCKETTIMEDOUT","connect":false},"isOperational":true,"code":"ESOCKETTIMEDOUT","connect":false},"request":{"method":"getblockstats","parameters":[672941]}}) +16ms
  btcexp:error Error 283h7ewsede: Error: RpcError: type=failure-02, json: {"userData":{"error":{"cause":{"code":"ESOCKETTIMEDOUT","connect":false},"isOperational":true,"code":"ESOCKETTIMEDOUT","connect":false},"request":{"method":"getblockstats","parameters":[672940]}}}, userData: [object Object] (json: {"error":{"cause":{"code":"ESOCKETTIMEDOUT","connect":false},"isOperational":true,"code":"ESOCKETTIMEDOUT","connect":false},"request":{"method":"getblockstats","parameters":[672940]}}) +15ms
  btcexp:error Error 283h7ewsede: Error: RpcError: type=failure-02, json: {"userData":{"error":{"cause":{"code":"ESOCKETTIMEDOUT","connect":false},"isOperational":true,"code":"ESOCKETTIMEDOUT","connect":false},"request":{"method":"getblockstats","parameters":[672939]}}}, userData: [object Object] (json: {"error":{"cause":{"code":"ESOCKETTIMEDOUT","connect":false},"isOperational":true,"code":"ESOCKETTIMEDOUT","connect":false},"request":{"method":"getblockstats","parameters":[672939]}}) +2s
  btcexp:error Error 283h7ewsede: Error: RpcError: type=failure-02, json: {"userData":{"error":{"cause":{"code":"ESOCKETTIMEDOUT","connect":false},"isOperational":true,"code":"ESOCKETTIMEDOUT","connect":false},"request":{"method":"getblockstats","parameters":[672938]}}}, userData: [object Object] (json: {"error":{"cause":{"code":"ESOCKETTIMEDOUT","connect":false},"isOperational":true,"code":"ESOCKETTIMEDOUT","connect":false},"request":{"method":"getblockstats","parameters":[672938]}}) +1ms
  btcexp:error Error 283h7ewsede: Error: RpcError: type=failure-02, json: {"userData":{"error":{"cause":{"code":"ESOCKETTIMEDOUT","connect":false},"isOperational":true,"code":"ESOCKETTIMEDOUT","connect":false},"request":{"method":"getblockstats","parameters":[672937]}}}, userData: [object Object] (json: {"error":{"cause":{"code":"ESOCKETTIMEDOUT","connect":false},"isOperational":true,"code":"ESOCKETTIMEDOUT","connect":false},"request":{"method":"getblockstats","parameters":[672937]}}) +1ms
  btcexp:error Error 283h7ewsede: Error: RpcError: type=failure-02, json: {"userData":{"error":{"cause":{"code":"ESOCKETTIMEDOUT","connect":false},"isOperational":true,"code":"ESOCKETTIMEDOUT","connect":false},"request":{"method":"getblockstats","parameters":[672936]}}}, userData: [object Object] (json: {"error":{"cause":{"code":"ESOCKETTIMEDOUT","connect":false},"isOperational":true,"code":"ESOCKETTIMEDOUT","connect":false},"request":{"method":"getblockstats","parameters":[672936]}}) +308ms
  btcexp:error Error 283h7ewsede: Error: RpcError: type=failure-02, json: {"userData":{"error":{"cause":{"code":"ESOCKETTIMEDOUT","connect":false},"isOperational":true,"code":"ESOCKETTIMEDOUT","connect":false},"request":{"method":"getblockstats","parameters":[672935]}}}, userData: [object Object] (json: {"error":{"cause":{"code":"ESOCKETTIMEDOUT","connect":false},"isOperational":true,"code":"ESOCKETTIMEDOUT","connect":false},"request":{"method":"getblockstats","parameters":[672935]}}) +2ms
Error: RpcError: type=failure-02
    at Client.<anonymous> (C:\Users\Calson\AppData\Roaming\npm\node_modules\btc-rpc-explorer\app\api\rpcApi.js:411:13)
    at Client.tryCatcher (C:\Users\Calson\AppData\Roaming\npm\node_modules\btc-rpc-explorer\node_modules\bluebird\js\release\util.js:16:23)
    at Promise.errorAdapter (C:\Users\Calson\AppData\Roaming\npm\node_modules\btc-rpc-explorer\node_modules\bluebird\js\release\nodeify.js:35:34)
    at Promise._settlePromise (C:\Users\Calson\AppData\Roaming\npm\node_modules\btc-rpc-explorer\node_modules\bluebird\js\release\promise.js:601:21)
    at Promise._settlePromise0 (C:\Users\Calson\AppData\Roaming\npm\node_modules\btc-rpc-explorer\node_modules\bluebird\js\release\promise.js:649:10)
    at Promise._settlePromises (C:\Users\Calson\AppData\Roaming\npm\node_modules\btc-rpc-explorer\node_modules\bluebird\js\release\promise.js:725:18)
    at _drainQueueStep (C:\Users\Calson\AppData\Roaming\npm\node_modules\btc-rpc-explorer\node_modules\bluebird\js\release\async.js:93:12)
    at _drainQueue (C:\Users\Calson\AppData\Roaming\npm\node_modules\btc-rpc-explorer\node_modules\bluebird\js\release\async.js:86:9)
    at Async._drainQueues (C:\Users\Calson\AppData\Roaming\npm\node_modules\btc-rpc-explorer\node_modules\bluebird\js\release\async.js:102:5)
    at Immediate.Async.drainQueues [as _onImmediate] (C:\Users\Calson\AppData\Roaming\npm\node_modules\btc-rpc-explorer\node_modules\bluebird\js\release\async.js:15:14)
    at processImmediate (internal/timers.js:461:21)
undefined:1
Work queue depth exceeded
^

SyntaxError: Unexpected token W in JSON at position 0
    at JSON.parse (<anonymous>)
    at obfuscateResponse (C:\Users\Calson\AppData\Roaming\npm\node_modules\btc-rpc-explorer\node_modules\bitcoin-core\dist\src\logging\request-obfuscator.js:60:23)
    at obfuscate (C:\Users\Calson\AppData\Roaming\npm\node_modules\btc-rpc-explorer\node_modules\bitcoin-core\dist\src\logging\request-obfuscator.js:142:3)
    at C:\Users\Calson\AppData\Roaming\npm\node_modules\btc-rpc-explorer\node_modules\bitcoin-core\dist\src\logging\request-logger.js:24:36
    at Request.<anonymous> (C:\Users\Calson\AppData\Roaming\npm\node_modules\btc-rpc-explorer\node_modules\@uphold\request-logger\src\index.js:33:9)
    at Request.emit (events.js:327:22)
    at Request.<anonymous> (C:\Users\Calson\AppData\Roaming\npm\node_modules\btc-rpc-explorer\node_modules\request\request.js:1154:10)
    at Request.emit (events.js:315:20)
    at IncomingMessage.<anonymous> (C:\Users\Calson\AppData\Roaming\npm\node_modules\btc-rpc-explorer\node_modules\request\request.js:1076:12)
    at Object.onceWrapper (events.js:421:28)
    at IncomingMessage.emit (events.js:327:22)
    at endReadableNT (internal/streams/readable.js:1327:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)`

seeing a similar error, but not sure if it is a configuration error.  rpc commands appear to work on bitcoind but become unavailable to btc-rpc-explorer. when btc-rpc-explorer server starts (using uri as parameter) it appears to make RPC commands rapidly and getting back connection socket timeouts ESOCKETTIMEOUT until it reaches Work queue depth error 

have not been able to get btc-rpc-explorer to work

Windows 10 nodejs v14.16.0

**Comment by ChAnDu353** [comment]
Facing the same issue on windows 10. fresh installation. on version 3.3
node v16.13.1   

 

`
 btcexp:app Environment(development) - Node: v16.13.1, Platform: win32, Versions: {"node":"16.13.1","v8":"9.4.146.24-node.14","uv":"1.42.0","zlib":"1.2.11","brotli":"1.0.9","ares":"1.18.1","modules":"93","nghttp2":"1.45.1","napi":"8","llhttp":"6.0.4","openssl":"1.1.1l+quic","cldr":"39.0","icu":"69.1","tz":"2021a","unicode":"13.0","ngtcp2":"0.1.0-DEV","nghttp3":"0.1.0-DEV"} +16ms
  btcexp:app No sourcecode version available, continuing to use default cacheId '3.3.0' +0ms
  btcexp:app Starting BTC RPC Explorer, v3.3.0 at http://127.0.0.1:3002/ +0ms
  btcexp:app Connecting to RPC node at 127.0.0.1:8332 +1ms
  btcexp:app Verifying RPC connection... +7ms
  btcexp:app Loading mining pools config +1ms
undefined:1
Work queue depth exceeded
^

SyntaxError: Unexpected token W in JSON at position 0
    at JSON.parse (<anonymous>)
    at obfuscateResponse (D:\nodejs\nodeWorks\btc-rpc-explorer\node_modules\btc-rpc-client\dist\src\logging\request-obfuscator.js:60:23)
    at obfuscate (D:\nodejs\nodeWorks\btc-rpc-explorer\node_modules\btc-rpc-client\dist\src\logging\request-obfuscator.js:142:3)
    at D:\nodejs\nodeWorks\btc-rpc-explorer\node_modules\btc-rpc-client\dist\src\logging\request-logger.js:24:36
    at Request.<anonymous> (D:\nodejs\nodeWorks\btc-rpc-explorer\node_modules\@uphold\request-logger\src\index.js:33:9)
    at Request.emit (node:events:402:35)
    at Request.<anonymous> (D:\nodejs\nodeWorks\btc-rpc-explorer\node_modules\request\request.js:1154:10)
    at Request.emit (node:events:390:28)
    at IncomingMessage.<anonymous> (D:\nodejs\nodeWorks\btc-rpc-explorer\node_modules\request\request.js:1076:12)
    at Object.onceWrapper (node:events:509:28)
    at IncomingMessage.emit (node:events:402:35)
    at endReadableNT (node:internal/streams/readable:1343:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
`

**Comment by janoside** [comment]
Cleaning up old issues. If you're still having this problem using the latest code (3.4-beta or greater), feel free to reply.

**Comment by burn1ngd0g** [comment]
> Cleaning up old issues. If you're still having this problem using the latest code (3.4-beta or greater), feel free to reply.

With latest docker image got the same issue after some times running : 

```
2024-11-20T09:05:10.388Z btcexp:app Searching for config files...
2024-11-20T09:05:10.389Z btcexp:app Config file not found at /root/.config/btc-rpc-explorer.env, continuing...
2024-11-20T09:05:10.389Z btcexp:app Config file not found at /etc/btc-rpc-explorer/.env, continuing...
2024-11-20T09:05:10.389Z btcexp:app Config file not found at /workspace/.env, continuing...
2024-11-20T09:05:10.389Z btcexp:app No config files found. Using all defaults.
2024-11-20T09:05:10.815Z btcexp:app Default cacheId '3.3.0'
2024-11-20T09:05:10.831Z btcexp:app Enabling view caching (performance will be improved but template edits will not be reflected)
Warning: connect.session() MemoryStore is not
designed for a production environment, as it will leak
memory, and will not scale past a single process.
2024-11-20T09:05:10.848Z btcexp:app Environment(production) - Node: v14.19.1, Platform: linux, Versions: {"node":"14.19.1","v8":"8.4.371.23-node.85","uv":"1.42.0","zlib":"1.2.11","brotli":"1.0.9","ares":"1.18.1","modules":"83","nghttp2":"1.42.0","napi":"8","llhttp":"2.1.4","openssl":"1.1.1n","cldr":"40.0","icu":"70.1","tz":"2021a3","unicode":"14.0"}
2024-11-20T09:05:10.861Z btcexp:app Using sourcecode version as cacheId: '794fb953b4'
2024-11-20T09:05:10.862Z btcexp:app Starting BTC RPC Explorer, v3.3.0 (commit: '794fb953b4', date: 2022-04-26) at http://0.0.0.0:3002/
2024-11-20T09:05:10.862Z btcexp:app Connecting to RPC node at 10.255.255.12:8332
2024-11-20T09:05:10.865Z btcexp:app Verifying RPC connection...
2024-11-20T09:05:10.866Z btcexp:app Loading mining pools config
undefined:1
Work queue depth exceeded
^

SyntaxError: Unexpected token W in JSON at position 0
    at JSON.parse (<anonymous>)
    at obfuscateResponse (/workspace/node_modules/btc-rpc-client/dist/src/logging/request-obfuscator.js:60:23)
    at obfuscate (/workspace/node_modules/btc-rpc-client/dist/src/logging/request-obfuscator.js:142:3)
    at /workspace/node_modules/btc-rpc-client/dist/src/logging/request-logger.js:24:36
    at Request.<anonymous> (/workspace/node_modules/@uphold/request-logger/src/index.js:33:9)
    at Request.emit (events.js:412:35)
    at Request.<anonymous> (/workspace/node_modules/request/request.js:1154:10)
    at Request.emit (events.js:400:28)
    at IncomingMessage.<anonymous> (/workspace/node_modules/request/request.js:1076:12)
    at Object.onceWrapper (events.js:519:28)
    at IncomingMessage.emit (events.js:412:35)
    at endReadableNT (internal/streams/readable.js:1334:12)
    at processTicksAndRejections (internal/process/task_queues.js:82:21)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! btc-rpc-explorer@3.3.0 start: `node ./bin/www`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the btc-rpc-explorer@3.3.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2024-11-20T09_05_10_896Z-debug.log

> btc-rpc-explorer@3.3.0 start /workspace
> node ./bin/www
```
