### ISSUE TITLE
Explorer won't load with Bitcoin 0.21.0

### ISSUE THREAD

**Issue by sangaman** [janoside/btc-rpc-explorer#263]
**Describe the bug**

I upgraded my bitcoin core node from 0.20 to 0.21.0 and btc-rpc-explorer stopped working. Loading it in the browser displays this error message.

```
Error loading recent blocks: Error: RpcError: type=failure-02
Error

/home/bitcoin/btc-rpc-explorer/views/includes/index-network-summary.pug:60
    58| 					td.text-right.text-monospace
    59| 						- var colorClass = "text-success";
  > 60| 						if (mempoolInfo.size > 7000)
    61| 							- colorClass = "text-warning";
    62| 						if (mempoolInfo.size > 11000)
    63| 							- colorClass = "text-danger";

Cannot read property 'size' of undefined

TypeError: /home/bitcoin/btc-rpc-explorer/views/includes/index-network-summary.pug:60
    58| 					td.text-right.text-monospace
    59| 						- var colorClass = "text-success";
  > 60| 						if (mempoolInfo.size > 7000)
    61| 							- colorClass = "text-warning";
    62| 						if (mempoolInfo.size > 11000)
    63| 							- colorClass = "text-danger";

Cannot read property 'size' of undefined
    at eval (eval at wrap (/home/bitcoin/btc-rpc-explorer/node_modules/pug-runtime/wrap.js:6:10), <anonymous>:1069:18)
    at template (eval at wrap (/home/bitcoin/btc-rpc-explorer/node_modules/pug-runtime/wrap.js:6:10), <anonymous>:6115:72)
    at Object.exports.renderFile (/home/bitcoin/btc-rpc-explorer/node_modules/pug/lib/index.js:427:38)
    at Object.exports.renderFile (/home/bitcoin/btc-rpc-explorer/node_modules/pug/lib/index.js:417:21)
    at exports.__express (/home/bitcoin/btc-rpc-explorer/node_modules/pug/lib/index.js:464:11)
    at View.engine (/home/bitcoin/btc-rpc-explorer/app.js:70:23)
    at View.render (/home/bitcoin/btc-rpc-explorer/node_modules/express/lib/view.js:135:8)
    at tryRender (/home/bitcoin/btc-rpc-explorer/node_modules/express/lib/application.js:640:10)
    at Function.render (/home/bitcoin/btc-rpc-explorer/node_modules/express/lib/application.js:592:3)
    at ServerResponse.render (/home/bitcoin/btc-rpc-explorer/node_modules/express/lib/response.js:1012:7)
    at /home/bitcoin/btc-rpc-explorer/routes/baseRouter.js:194:9
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
```

**Environment (please complete the following information):**

 - Bitcoin Core 0.21.0rc3
 - NodeJS Version 14.15.1
 - Browser Firefox
 - Code Version / Commit 65f63a7d9acf7423dece3303d8e48a7de0088c75

**Comment by janoside** [comment]
Looking into this...do you have any output from the app log? Or just this browser error? I'm running a Bitcoin Core I built from source last week and am not seeing this so far.

**Comment by sangaman** [comment]
Oddly, the error has gone away with no further intervention. I wonder if it had to do with syncing to catch up with the blockchain tip? I thought I had fully synced but maybe there was still some txindex updates going on. It did look like there was a delay before the error came up and this is a resource constrained system, so maybe it's due to some sort of timeout.

**Comment by sangaman** [comment]
Should I close this since the issue seems to have been transient? There might be some minor bug/error handling issue to address here when bitcoind is still syncing or slow to respond to rpc commands, but I don't think 0.21.0 is the problem.

**Comment by janoside** [comment]
Yes, I'll go ahead and close. I do have some minor error handling improvements / armor that I'll add because of this, but I'm glad it doesn't seem to be a 0.21 issue.
