### ISSUE TITLE
User Report: Undefined "userSettings" when trying to select theme

### ISSUE THREAD

**Issue by janoside** [janoside/btc-rpc-explorer#311]
The below error was encountered when upgrading from 2.2 to 3.1. When SSO was disabled, the error was resolved.

```
TypeError: /opt/mynode/btc-rpc-explorer/views/layout.pug:15
    13| 
    14| 
  > 15| if (userSettings.uiTheme == "light")
    16| link(rel="stylesheet", href="./style/light.css", integrity="sha384-g29RQdd+TbXjjBSuwxb0PuDyrEcBhwSZ7JRL21EgNUQsP7XAXGvjiP1EhgHnL/Hj")
    17| 
    18| else

Cannot read property 'uiTheme' of undefined
    at eval (eval at wrap (/opt/mynode/btc-rpc-explorer/node_modules/pug-runtime/wrap.js:6:10), <anonymous>:29:19)
    at template (eval at wrap (/opt/mynode/btc-rpc-explorer/node_modules/pug-runtime/wrap.js:6:10), <anonymous>:4854:7)
    at Object.exports.renderFile (/opt/mynode/btc-rpc-explorer/node_modules/pug/lib/index.js:454:38)
    at Object.exports.renderFile (/opt/mynode/btc-rpc-explorer/node_modules/pug/lib/index.js:444:21)
    at exports.__express (/opt/mynode/btc-rpc-explorer/node_modules/pug/lib/index.js:493:11)
    at View.expressApp.engine (/opt/mynode/btc-rpc-explorer/app.js:120:23)
    at View.render (/opt/mynode/btc-rpc-explorer/node_modules/express/lib/view.js:135:8)
    at tryRender (/opt/mynode/btc-rpc-explorer/node_modules/express/lib/application.js:640:10)
    at Function.render (/opt/mynode/btc-rpc-explorer/node_modules/express/lib/application.js:592:3)
    at ServerResponse.render (/opt/mynode/btc-rpc-explorer/node_modules/express/lib/response.js:1012:7)
    at /opt/mynode/btc-rpc-explorer/app.js:802:6
    at Layer.handle_error (/opt/mynode/btc-rpc-explorer/node_modules/express/lib/router/layer.js:71:5)
    at trim_prefix (/opt/mynode/btc-rpc-explorer/node_modules/express/lib/router/index.js:315:13)
    at /opt/mynode/btc-rpc-explorer/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/opt/mynode/btc-rpc-explorer/node_modules/express/lib/router/index.js:335:12)
    at http://IncomingMessage.next (/opt/mynode/btc-rpc-explorer/node_modules/express/lib/router/index.js:275:10)


```

**Comment by Kixunil** [comment]
Yeah, I was hit by this as well.

**Comment by janoside** [comment]
@Kixunil Just pushed a PR trying to address this. It works for me but I'd be happy to have you review/test and let me know what you find.

**Comment by Kixunil** [comment]
Now there is another error but at least I can click around in tools.

```
/usr/lib/btc-rpc-explorer/views/includes/index-network-summary.pug:75
    73| 
    74| +contentSection
  > 75| 	+summaryRow(1 + (hashrate7d ? 1 : 0) + (chainTxStats[7 * targetBlocksPerDay] ? 1 : 0) + (difficultyAdjustmentData ? 1 : 0))
    76| 		if (hashrate7d)
    77| 			+summaryItem("7d Hashrate", "The average hashrate of the global mining network over the last 7 days. A comparison to the 30-day average is included to help gauge the rate of change.")
    78| 				- var hashrate7dayData = utils.formatLargeNumber(hashrate7d, 1);

Cannot read property '1008' of undefined

TypeError: /usr/lib/btc-rpc-explorer/views/includes/index-network-summary.pug:75
    73| 
    74| +contentSection
  > 75| 	+summaryRow(1 + (hashrate7d ? 1 : 0) + (chainTxStats[7 * targetBlocksPerDay] ? 1 : 0) + (difficultyAdjustmentData ? 1 : 0))
    76| 		if (hashrate7d)
    77| 			+summaryItem("7d Hashrate", "The average hashrate of the global mining network over the last 7 days. A comparison to the 30-day average is included to help gauge the rate of change.")
    78| 				- var hashrate7dayData = utils.formatLargeNumber(hashrate7d, 1);

Cannot read property '1008' of undefined
    at block (eval at wrap (/usr/lib/btc-rpc-explorer/node_modules/pug-runtime/wrap.js:6:10), <anonymous>:4896:44)
    at Object.pug_interp (eval at wrap (/usr/lib/btc-rpc-explorer/node_modules/pug-runtime/wrap.js:6:10), <anonymous>:174:10)
    at eval (eval at wrap (/usr/lib/btc-rpc-explorer/node_modules/pug-runtime/wrap.js:6:10), <anonymous>:4736:30)
    at template (eval at wrap (/usr/lib/btc-rpc-explorer/node_modules/pug-runtime/wrap.js:6:10), <anonymous>:7471:7)
    at Object.exports.renderFile (/usr/lib/btc-rpc-explorer/node_modules/pug/lib/index.js:454:38)
    at Object.exports.renderFile (/usr/lib/btc-rpc-explorer/node_modules/pug/lib/index.js:444:21)
    at exports.__express (/usr/lib/btc-rpc-explorer/node_modules/pug/lib/index.js:493:11)
    at View.expressApp.engine (/usr/lib/btc-rpc-explorer/app.js:120:23)
    at View.render (/usr/lib/btc-rpc-explorer/node_modules/express/lib/view.js:135:8)
    at tryRender (/usr/lib/btc-rpc-explorer/node_modules/express/lib/application.js:640:10)
    at Function.render (/usr/lib/btc-rpc-explorer/node_modules/express/lib/application.js:592:3)
    at ServerResponse.render (/usr/lib/btc-rpc-explorer/node_modules/express/lib/response.js:1012:7)
    at router.get.asyncHandler (/usr/lib/btc-rpc-explorer/routes/baseRouter.js:279:7)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

![btc-rpc-explorer-bug](https://user-images.githubusercontent.com/1178779/115087746-0dd01a80-9f0f-11eb-83ff-36a09e574729.png)

**Comment by janoside** [comment]
@Kixunil Haven't been testing against regtest much lately. Looks like there were a few regtest problems with the homepage. Just pushed some minor fixes.

I guess this means that the SSO issue is resolved?

**Comment by Kixunil** [comment]
Isn't regtest supposed to have the same code as mainnet modulo some graphics?

Looks like `chainTxStats` is undefined and I don't see why it should be undefined on regtest.

I will try to look at mainnet and let you know.

**Comment by janoside** [comment]
There's not much difference between regtest/mainnet, but there's some, mostly out of simplification/convenience. Reducing/eliminating the differences seems like a good goal, just not a priority at the moment.

https://github.com/janoside/btc-rpc-explorer/blob/master/routes/baseRouter.js#L169

**Comment by Kixunil** [comment]
Mainnet works. (Tested only in clean VM, so IBD in progress but hopefully it's OK.)
