### ISSUE TITLE
Error: connect ECONNREFUSED 127.0.0.1:50001

### ISSUE THREAD

**Issue by derrickr** [janoside/btc-rpc-explorer#370]
Just updated to latest version v3.2.0 and now seeing errors.

Environment:
 - Bitcoin Core  = v22
 - NodeJS Version v14.17.6
 - npm = 7.24.0
 - Installation Method "npm"

bitcoin.conf
>server=1
>blockfilterindex=1
>txindex=1
>daemon=1
>rpcport=8332
>rpcbind=0.0.0.0
>rpcallowip=127.0.0.1
>rpcallowip=10.0.0.0/8
>rpcallowip=172.0.0.0/8
>rpcallowip=192.0.0.0/8
>zmqpubrawblock=tcp://0.0.0.0:28332
>zmqpubrawtx=tcp://0.0.0.0:28333
>zmqpubhashblock=tcp://0.0.0.0:28334
>rpcuser=XXXXXXX
>rpcpassword=XXXXXXX
>proxy=127.0.0.1:9050
>listen=1
>onlynet=onion
>bind=127.0.0.1
>dnsseed=0
>dns=0
>listenonion=1

btc-rpc-explorer.env
>BTCEXP_HOST=0.0.0.0
>BTCEXP_ADDRESS_API=electrumx
>BTCEXP_SLOW_DEVICE_MODE=false
>BTCEXP_NO_RATES=false
>BTCEXP_BASIC_AUTH_PASSWORD=XXXXXXX
>BTCEXP_UI_SHOW_TOOLS_SUBHEADER=true

**To Reproduce**
>sudo systemctl status btc-rpc-explorer.service

**Output**
> ● btc-rpc-explorer.service - btc-rpc-explorer
>     Loaded: loaded (/etc/systemd/system/btc-rpc-explorer.service; enabled; vendor preset: enabled)
>     Active: active (running) since Sat 2021-09-18 14:37:06 BST; 6min ago
>   Main PID: 719 (npm start)
>      Tasks: 23 (limit: 38122)
>     Memory: 126.4M
>     CGroup: /system.slice/btc-rpc-explorer.service
>             ├─ 719 npm start
>             ├─1016 sh -c node ./bin/www
>             └─1022 node ./bin/www>>
>
>Sep 18 14:42:57 fullNode npm[1022]:     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1148:16)
>Sep 18 14:42:57 fullNode npm[1022]: 2021-09-18T13:42:57.832Z btcexp:error Error 937gf47dsyde: Error: connect ECONNREFUSED 127.0.0.1:50001, json: {"errno":-111,"code":"ECONNREFUSED","syscall":"connect","address":"127.0.0.1","port":50001}, userData: [object Object] (json: {"host":"127.0.0.1","port":50001,"protocol":"tcp","errorMsg":"connect ECONNREFUSED 127.0.0.1:50001"})
>Sep 18 14:42:57 fullNode npm[1022]: 2021-09-18T13:42:57.832Z btcexp:errorVerbose Stack: Error: connect ECONNREFUSED 127.0.0.1:50001
>Sep 18 14:42:57 fullNode npm[1022]:     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1148:16)
>Sep 18 14:43:07 fullNode npm[1022]: 2021-09-18T13:43:07.833Z btcexp:error Error 937gf47dsyde: Error: connect ECONNREFUSED 127.0.0.1:50001, json: {"errno":-111,"code":"ECONNREFUSED","syscall":"connect","address":"127.0.0.1","port":50001}, userData: [object Object] (json: {"host":"127.0.0.1","port":50001,"protocol":"tcp","errorMsg":"connect ECONNREFUSED 127.0.0.1:50001"})
>Sep 18 14:43:07 fullNode npm[1022]: 2021-09-18T13:43:07.833Z btcexp:errorVerbose Stack: Error: connect ECONNREFUSED 127.0.0.1:50001
>Sep 18 14:43:07 fullNode npm[1022]:     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1148:16)
>Sep 18 14:43:07 fullNode npm[1022]: 2021-09-18T13:43:07.833Z btcexp:error Error 937gf47dsyde: Error: connect ECONNREFUSED 127.0.0.1:50001, json: {"errno":-111,"code":"ECONNREFUSED","syscall":"connect","address":"127.0.0.1","port":50001}, userData: [object Object] (json: {"host":"127.0.0.1","port":50001,"protocol":"tcp","errorMsg":"connect ECONNREFUSED 127.0.0.1:50001"})
>Sep 18 14:43:07 fullNode npm[1022]: 2021-09-18T13:43:07.833Z btcexp:errorVerbose Stack: Error: connect ECONNREFUSED 127.0.0.1:50001
>Sep 18 14:43:07 fullNode npm[1022]:     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1148:16)

I'd appreciate any help, Cheers!

**Comment by derrickr** [comment]
Guess it was a timing thing!?

All good now!
