### ISSUE TITLE
Will not run on install - ECONNREFUSED

### ISSUE THREAD

**Issue by ahuw** [janoside/btc-rpc-explorer#399]
**Describe the bug**

I have installed btc-rpc-explorer following https://raspibolt.org/btcrpcexplorer.html#btc-rpc-explorer but on npm run start I get errors

**Environment (please complete the following information):**

 - Bitcoin Core / Node Version 22.0.0
 - NodeJS Version v14.18.2
 - Browser firefox
 - Code Version / Commit 581ad524cd
 - Installation Method npm
 
**Configuration file content**

 - bitcoin.conf

server=1
txindex=1

listen=1
listenonion=1
proxy=127.0.0.1:9050
bind=127.0.0.1

rpcauth=******:*******************
zmqpubrawblock=tcp://127.0.0.1:28332
zmqpubrawtx=tcp://127.0.0.1:28333
whitelist=download@127.0.0.1          # for Electrs

maxconnections=40
maxuploadtarget=5000

 - Your btc-rpc-explorer environment configuration (either `$WORKING_DIR/.env` or `~/.config/btc-rpc-explorer.env`)

BTCEXP_BITCOIND_HOST=newRaspberry.local
BTCEXP_BITCOIND_PORT=8332
#BTCEXP_BITCOIND_USER=
#BTCEXP_BITCOIND_PASS=
BTCEXP_BITCOIND_COOKIE=/data/bitcoin/.cookie
BTCEXP_BITCOIND_RPC_TIMEOUT=10000

BTCEXP_ADDRESS_API=electrum

BTCEXP_ELECTRUM_SERVERS=tcp://newRaspberry.local:50001

BTCEXP_PRIVACY_MODE=false

BTCEXP_NO_RATES=false
BTCEXP_UI_THEME=dark

**To Reproduce**

npm run start

> btc-rpc-explorer@3.3.0 start /home/btcrpcexplorer/btc-rpc-explorer
> node ./bin/www

  btcexp:app Searching for config files... +0ms
  btcexp:app Config file not found at /home/btcrpcexplorer/.config/btc-rpc-explorer.env, continuing... +4ms
  btcexp:app Config file not found at /etc/btc-rpc-explorer/.env, continuing... +0ms
  btcexp:app Config file found at /home/btcrpcexplorer/btc-rpc-explorer/.env, loading... +0ms
Loading RPC cookie file: /data/bitcoin/.cookie
  btcexp:app Default cacheId '3.3.0' +2s
  btcexp:app Enabling view caching (performance will be improved but template edits will not be reflected) +57ms
  btcexp:app Environment(development) - Node: v14.18.2, Platform: linux, Versions: {"node":"14.18.2","v8":"8.4.371.23-node.85","uv":"1.42.0","zlib":"1.2.11","brotli":"1.0.9","ares":"1.18.1","modules":"83","nghttp2":"1.42.0","napi":"8","llhttp":"2.1.4","openssl":"1.1.1l","cldr":"39.0","icu":"69.1","tz":"2021a","unicode":"13.0"} +18ms
  btcexp:app Using sourcecode version as cacheId: '581ad524cd' +39ms
  btcexp:app Starting BTC RPC Explorer, v3.3.0 (commit: '581ad524cd', date: 2021-12-12) at http://127.0.0.1:3002/ +1ms
  btcexp:app Connecting to RPC node at newRaspberry.local:8332 +1ms
  btcexp:app Verifying RPC connection... +16ms
  btcexp:app Loading mining pools config +10ms
  btcexp:error Error RpcError-001: Error: connect ECONNREFUSED 192.168.1.17:8332, json: {"errno":-111,"code":"ECONNREFUSED","syscall":"connect","address":"192.168.1.17","port":8332,"userData":{"request":"getnetworkinfo"}}, userData: [object Object] (json: {"request":"getnetworkinfo"}) +0ms
  btcexp:errorVerbose Stack: Error: connect ECONNREFUSED 192.168.1.17:8332
  btcexp:errorVerbose     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1159:16) +0ms
  btcexp:error Error 32ugegdfsde: Error: connect ECONNREFUSED 192.168.1.17:8332, json: {"errno":-111,"code":"ECONNREFUSED","syscall":"connect","address":"192.168.1.17","port":8332,"userData":{"request":"getnetworkinfo"}}, userData: [object Object] (json: {}) +3ms
  btcexp:errorVerbose Stack: Error: connect ECONNREFUSED 192.168.1.17:8332
  btcexp:errorVerbose     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1159:16) +2ms
  btcexp:error Error 937gf47dsyde: Error: connect ECONNREFUSED 192.168.1.17:50001, json: {"errno":-111,"code":"ECONNREFUSED","syscall":"connect","address":"192.168.1.17","port":50001}, userData: [object Object] (json: {"host":"newraspberry.local","port":50001,"protocol":"tcp"}) +3ms
  btcexp:errorVerbose Stack: Error: connect ECONNREFUSED 192.168.1.17:50001
  btcexp:errorVerbose     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1159:16) +4ms
  btcexp:error Error 120387rygxx231gwe40: Error: connect ECONNREFUSED 192.168.1.17:50001, json: {"errno":-111,"code":"ECONNREFUSED","syscall":"connect","address":"192.168.1.17","port":50001}, userData: [object Object] (json: {}) +2ms
  btcexp:errorVerbose Stack: Error: connect ECONNREFUSED 192.168.1.17:50001

etc.

**Additional context**

I have read all issues that seemed related and searched online.

**Comment by ahuw** [comment]
Is it related to this? The blockchain has downloaded but something may be wrong.

~ $ bitcoin-cli getblockchaininfo
{
  "chain": "main",
  "blocks": 716420,
  "headers": 716420,
  "bestblockhash": "0000000000000000000645d7670d06cdd500fb82ccc8f2bea9b2e5d61720983f",
  "difficulty": 24272331996979.97,
  "mediantime": 1640880822,
  "verificationprogress": 0.9999972629601385,
  "initialblockdownload": false,
etc.

I previously had this, which shows progress=1.00:
~ $ systemctl status bitcoind.service
* bitcoind.service - Bitcoin daemon
     Loaded: loaded (/etc/systemd/system/bitcoind.service; enabled; vendor preset: enabled)
     Active: active (running) since Sun 2021-12-26 00:17:07 GMT; 17h ago
    Process: 586 ExecStart=/usr/local/bin/bitcoind -daemon -pid=/run/bitcoind/bitcoind.pid -conf=/home/bitcoin/.bitcoin/bitcoin.conf -datadir=/home/bitcoin/.bitcoin -startupnotify=chmod g+r /home/bitcoin/.bitcoin/.cookie (code=exited, status=0/SUCCESS)
   Main PID: 619 (bitcoind)
      Tasks: 18 (limit: 4915)
        CPU: 29min 42.497s
     CGroup: /system.slice/bitcoind.service
             `-619 /usr/local/bin/bitcoind -daemon -pid=/run/bitcoind/bitcoind.pid -conf=/home/bitcoin/.bitcoin/bitcoin.conf -datadir=/home/bitcoin/.bitcoin -startupnotify=chmod g+r /home/bitcoin/.bitcoin/.cookie

Warning: some journal files were not opened due to insufficient permissions.
admin@pi:~ $ sudo tail -f /home/bitcoin/.bitcoin/debug.log
[sudo] password for admin:
2021-12-26T17:54:57Z UpdateTip: new best=000000000000000000091e13fb82731169027828a180eb25968b1e9aa96a5b3a height=715864 version=0x20000004 log2_work=93.251115 tx=698003870 date='2021-12-26T17:38:49Z' progress=0.999997 cache=200.3MiB(1799398txo)
2021-12-26T17:54:58Z UpdateTip: new best=0000000000000000000aff4c81396086c44e452cad2d24205c437dc0a957f09f height=715865 version=0x20600004 log2_work=93.251127 tx=698005550 date='2021-12-26T17:46:53Z' progress=0.999998 cache=200.7MiB(1803077txo)
2021-12-26T17:55:15Z UpdateTip: new best=00000000000000000009a94385218bd86808b9b0ebb2173bd0b59fc2d606cc0e height=715866 version=0x3fffe004 log2_work=93.251140 tx=698006715 date='2021-12-26T17:52:29Z' progress=0.999999 cache=200.9MiB(1804388txo)
2021-12-26T17:55:15Z UpdateTip: new best=0000000000000000000817da36b389d106d0d3370bdf3d6e822eb6f400eb413c height=715867 version=0x20000000 log2_work=93.251153 tx=698007093 date='2021-12-26T17:53:51Z' progress=1.000000 cache=200.9MiB(1805166txo)
2021-12-26T17:55:15Z UpdateTip: new best=00000000000000000004c8ef976712256e4546b9acde2eb23671e0bca68b5753 height=715868 version=0x20c00004 log2_work=93.251166 tx=698007094 date='2021-12-26T17:53:53Z' progress=1.000000 cache=200.9MiB(1805167txo)
2021-12-26T17:55:20Z New outbound peer connected: version: 70015, blocks=715868, peer=25 (block-relay-only)

**Comment by ahuw** [comment]
I think it's a permissions problem. I tried to update

btcrpcexplorer@newRaspberry:~/btc-rpc-explorer $ npm install -g npm

and got 

npm WARN checkPermissions Missing write access to /usr/lib/node_modules/npm/node_modules/abbrev
etc.

The permissions are rwxr-xr-x and owner and group are root

**Comment by ahuw** [comment]
I changed BTCEXP_BITCOIND_HOST=newRaspberry.local
to BTCEXP_BITCOIND_HOST=127.0.01 as it should have been and it seems to work now
