### ISSUE TITLE
Transaction stats: Error 500: Work queue depth exceeded

### ISSUE THREAD

**Issue by Stadicus** [janoside/btc-rpc-explorer#49]
Running your fantastic block explorer on an Odroid HC2 with Debian, everything working very nicely.

Only when clicking on "Transaction stats" I can see on the console that the following error is generated, and the page is loading indefinitely.

```
  message: 'Internal Server Error',
  body: 'Work queue depth exceeded',
  code: 500,
  name: 'RpcError' } stack: RpcError: Internal Server Error
    at Client.rpc (/home/web/btc-rpc-explorer/node_modules/bitcoin-core/dist/src/parser.js:73:13)
    at Client.tryCatcher (/home/web/btc-rpc-explorer/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/web/btc-rpc-explorer/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/home/web/btc-rpc-explorer/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/home/web/btc-rpc-explorer/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/home/web/btc-rpc-explorer/node_modules/bluebird/js/release/promise.js:694:18)
    at Promise._fulfill (/home/web/btc-rpc-explorer/node_modules/bluebird/js/release/promise.js:638:18)
    at Request._callback (/home/web/btc-rpc-explorer/node_modules/bluebird/js/release/nodeback.js:45:21)
    at Request.self.callback (/home/web/btc-rpc-explorer/node_modules/request/request.js:186:22)
    at emitTwo (events.js:131:20)
    at Request.emit (events.js:214:7)
    at Request.<anonymous> (/home/web/btc-rpc-explorer/node_modules/request/request.js:1163:10)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at IncomingMessage.<anonymous> (/home/web/btc-rpc-explorer/node_modules/request/request.js:1085:12)
    at Object.onceWrapper (events.js:313:30)
```

No big deal, but maybe it helps to point out possible improvements.

On the third click it went through and the graphs were shown.

**Comment by janoside** [comment]
This should be fixed as of ff87228.
