### ISSUE TITLE
SyntaxError: Unexpected token [

### ISSUE THREAD

**Issue by martinschwarz** [janoside/btc-rpc-explorer#52]
I see the following error:
---
blk@e8020:~/Elements/work/btc-rpc-explorer$ npm start

> btc-rpc-explorer@1.0.0 start /media/blk/Elements/work/btc-rpc-explorer
> node ./bin/www

/media/blk/Elements/work/btc-rpc-explorer/app/utils.js:360
        var [lead,decimal,pow] = val.toString().split(/e|\./);
            ^

SyntaxError: Unexpected token [
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/media/blk/Elements/work/btc-rpc-explorer/app.js:14:13)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:417:10)

npm ERR! Linux 4.10.0-32-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "start"
npm ERR! node v4.2.6
npm ERR! npm  v3.5.2
npm ERR! code ELIFECYCLE
npm ERR! btc-rpc-explorer@1.0.0 start: `node ./bin/www`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the btc-rpc-explorer@1.0.0 start script 'node ./bin/www'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the btc-rpc-explorer package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./bin/www
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs btc-rpc-explorer
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls btc-rpc-explorer
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /media/blk/Elements/work/btc-rpc-explorer/npm-debug.log
----

**Comment by janoside** [comment]
I'm guessing this is due to your version of node being rather old. Any chance you could update it and try again? The docs should mention the minimum acceptable versions of various dependencies, but I admit I'm not exactly sure what they are. If you give it a try it could help me pin that down.
