### ISSUE TITLE
Timeout Error with Raspberry Pi

### ISSUE THREAD

**Issue by PatrickLemke** [janoside/btc-rpc-explorer#58]
### Setup
Raspberry Pi 3 B+ with external HDD (1TB)
Linux raspberrypi 4.14.62-v7+ #1134 SMP Tue Aug 14 17:10:10 BST 2018 armv7l GNU/Linux
Nodejs: v8.11.1
Npm: 6.4.1
Bitcoin Core Daemon version v0.17.99.0-bb0277819

When trying to connect to the Website with my Browser, I get this error. My suspicion is that my Raspberry Pi ist just very slow since the SD card and HDD are not the fastest. I have it running with Litecoin on my other Raspberry Pi without problems.

### Error Message
Unhandled Rejection at: Promise Promise {
  _bitField: 154402816,
  _fulfillmentHandler0:
   { Error: ESOCKETTIMEDOUT
    at ClientRequest.<anonymous> (/home/pi/btc-rpc-explorer/node_modules/request/request.js:813:19)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:106:13)
    at ClientRequest.emit (events.js:208:7)
    at Socket.emitTimeout (_http_client.js:711:34)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:106:13)
    at Socket.emit (events.js:208:7)
    at Socket._onTimeout (net.js:420:8)
    at ontimeout (timers.js:482:11)
    at tryOnTimeout (timers.js:317:5)
    at Timer.listOnTimeout (timers.js:277:5)
     cause: { Error: ESOCKETTIMEDOUT
    at ClientRequest.<anonymous> (/home/pi/btc-rpc-explorer/node_modules/request/request.js:813:19)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:106:13)
    at ClientRequest.emit (events.js:208:7)
    at Socket.emitTimeout (_http_client.js:711:34)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:106:13)
    at Socket.emit (events.js:208:7)
    at Socket._onTimeout (net.js:420:8)
    at ontimeout (timers.js:482:11)
    at tryOnTimeout (timers.js:317:5)
    at Timer.listOnTimeout (timers.js:277:5) code: 'ESOCKETTIMEDOUT', connect: false },
     isOperational: true,
     code: 'ESOCKETTIMEDOUT',
     connect: false },
  _rejectionHandler0: undefined,
  _promise0: undefined,
  _receiver0: undefined,
  _boundTo:
   Client {
     agentOptions: undefined,
     auth:
      { pass: 'xxx=',
        user: 'xxx' },
     hasNamedParametersSupport: false,
     headers: false,
     host: '127.0.0.1',
     password: 'xxx=',
     port: 8332,
     timeout: 5000,
     ssl: { enabled: false, strict: false },
     request:
      { [Function]
        get: [Function],
        head: [Function],
        post: [Function],
        put: [Function],
        patch: [Function],
        del: [Function],
        delete: [Function],
        cookie: [Function],
        jar: [Function],
        defaults: [Function],
        getAsync: [Function: ret],
        headAsync: [Function: ret],
        postAsync: [Function: ret],
        putAsync: [Function: ret],
        patchAsync: [Function: ret],
        delAsync: [Function: ret],
        deleteAsync: [Function: ret],
        cookieAsync: [Function: ret],
        jarAsync: [Function: ret],
        defaultsAsync: [Function: ret] },
     requester: Requester { unsupported: [], version: undefined },
     parser: Parser { headers: false } } } reason: { Error: ESOCKETTIMEDOUT
    at ClientRequest.<anonymous> (/home/pi/btc-rpc-explorer/node_modules/request/request.js:813:19)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:106:13)
    at ClientRequest.emit (events.js:208:7)
    at Socket.emitTimeout (_http_client.js:711:34)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:106:13)
    at Socket.emit (events.js:208:7)
    at Socket._onTimeout (net.js:420:8)
    at ontimeout (timers.js:482:11)
    at tryOnTimeout (timers.js:317:5)
    at Timer.listOnTimeout (timers.js:277:5)
  cause: { Error: ESOCKETTIMEDOUT
    at ClientRequest.<anonymous> (/home/pi/btc-rpc-explorer/node_modules/request/request.js:813:19)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:106:13)
    at ClientRequest.emit (events.js:208:7)
    at Socket.emitTimeout (_http_client.js:711:34)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:106:13)
    at Socket.emit (events.js:208:7)
    at Socket._onTimeout (net.js:420:8)
    at ontimeout (timers.js:482:11)
    at tryOnTimeout (timers.js:317:5)
    at Timer.listOnTimeout (timers.js:277:5) code: 'ESOCKETTIMEDOUT', connect: false },
  isOperational: true,
  code: 'ESOCKETTIMEDOUT',
  connect: false } stack: Error: ESOCKETTIMEDOUT
    at ClientRequest.<anonymous> (/home/pi/btc-rpc-explorer/node_modules/request/request.js:813:19)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:106:13)
    at ClientRequest.emit (events.js:208:7)
    at Socket.emitTimeout (_http_client.js:711:34)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:106:13)
    at Socket.emit (events.js:208:7)
    at Socket._onTimeout (net.js:420:8)
    at ontimeout (timers.js:482:11)
    at tryOnTimeout (timers.js:317:5)
    at Timer.listOnTimeout (timers.js:277:5)

**Comment by Smiggel** [comment]
It's not a Pi being slow issue. I run a Lightning node on a Pi 2 and run this explorer on the same machine as well. 👍 

Did you open port 3002 in the firewall of your pi?

**Comment by dawiepoolman** [comment]
I have the same setup and I also get timeouts when trying to connect to my RPi3 from my laptop.
The timeout messages occur when I run on my laptop:
npm start

**Comment by dawiepoolman** [comment]
I have also tried changing the bitcoin port to 8333 in credentials.js (instead of the 8332 as the default) but no luck yet.  I doubt it can be a timeout because of speed.  It might be related to rpc credentials/config..

**Comment by dawiepoolman** [comment]
My bad.  Seems like 8332 is reserved as the rpc port for bitcoin.  We might have to give it explicit firewall access on the RPi..

**Comment by PatrickLemke** [comment]
It does work for me if I select /peers for example. I think it is just a timeout error with the requests module of nodejs

**Comment by dawiepoolman** [comment]
I have managed to run it by referencing my full node on my laptop but I cant seem to get it running when pointing to the RPi LAN IP and rpc credentials of the pi.  I have also explicitly gave only my laptop LAN ip access through my Pis firewall but no joy.

I think you are right that it is highly likely to be the request.js module somewhere around line 843 being too aggressive with the timeout logic.

**Comment by gdassori** [comment]
The RPC timeout is quite strict. I would love to customize it. Thanks.

**Comment by PatrickLemke** [comment]
Thank you very much, this solved the issue for me.
