### ISSUE TITLE
Transcations and blocks are missing with Electrs

### ISSUE THREAD

**Issue by sha-265** [janoside/btc-rpc-explorer#636]
**Describe the bug**

When I'm trying to search for an address with transactions, I can see the transactions count, but the list of the transactions are empty. 
![image](https://github.com/janoside/btc-rpc-explorer/assets/4103710/32d70fa9-0b0f-440e-843d-3f8c03f12ab3)

Also if I'm trying to search this transaction, by it's ID, I can't find it (and other transactions also):
![image](https://github.com/janoside/btc-rpc-explorer/assets/4103710/696a715c-5802-4781-82ac-0cc5fb559f8c)

And for some reason some blocks are missing too. For example block 836999 missing (but 836,998 and 837,000 are ok):
![image](https://github.com/janoside/btc-rpc-explorer/assets/4103710/20f5b9da-d60d-4011-bb6b-2281d25b486e)

**Environment (please complete the following information):**

 - Bitcoin Core / Node Version [e.g. 0.16.3]: 22.1
 - NodeJS Version [e.g. 9.x]: v18.19.1
 - Code Version / Commit [e.g. ab6cde8]: v3.4.0
 - Installation Method [e.g. "npm" or "source code"]: npm
 - Electrs: v0.10.4
 
**Configuration file content**

Please include the content from the following files. **BE SURE TO MODIFY YOUR CREDENTIALS BEFORE SUBMITTING!!!**
 - bitcoin.conf
 ```
 txindex=1
server=1
 ```
 - Your btc-rpc-explorer environment configuration (either `$WORKING_DIR/.env` or `~/.config/btc-rpc-explorer.env`):
 ```
 BTCEXP_BITCOIND_RPC_TIMEOUT=32000
NODE_ENV="production"
BTCEXP_ADDRESS_API=electrum
BTCEXP_ELECTRUM_SERVERS=tcp://127.0.0.1:50005
BTCEXP_HOST=0.0.0.0
```

**To Reproduce**

1. Try to load block 837,000
2. See if it working

**Screenshots or Log Output**

```
 express:router dispatching GET /block-height/836999 +1m
  express:router query  : /block-height/836999 +1ms
  express:router expressInit  : /block-height/836999 +0ms
  express:router middleware  : /block-height/836999 +0ms
  express:router cookieParser  : /block-height/836999 +0ms
  express:router jsonParser  : /block-height/836999 +0ms
  body-parser:json skip empty body +1m
  express:router urlencodedParser  : /block-height/836999 +0ms
  body-parser:urlencoded skip empty body +0ms
  express:router session  : /block-height/836999 +0ms
  express-session fetching session-1ub-NRinOcz +1m
  memorystore GET "session-1ub-NRinOcz" +1m
  memorystore GOT {"cookie":{"originalMaxAge":null,"expires":null,"secure":false,"httpOnly":true,"path":"/"},"host":"127.0.0.1","port":8332,"username":"__cookie__","userSettings":{"displayCurrency":"btc","localCurrency":"usd","uiTimezone":"local","uiTheme":"dark"},"csrfSecret":"","query":null} +0ms
  express-session session found +0ms
  express:router compression  : /block-height/836999 +1ms
  express:router serveStatic  : /block-height/836999 +0ms
  send stat "/home/user/.nvm/versions/node/v18.19.1/lib/node_modules/btc-rpc-explorer/public/block-height/836999" +1m
  express:router <anonymous>  : /block-height/836999 +1ms
  express:router <anonymous>  : /block-height/836999 +0ms
  express:router csrf  : /block-height/836999 +0ms
  express:router <anonymous>  : /block-height/836999 +0ms
  express:router router  : /block-height/836999 +0ms
  express:router dispatching GET /block-height/836999 +0ms
  btcexp:rpc RPC: {"method":"getrawtransaction","parameters":["<some unknown txid>",1]} +1m
  btcexp:error Error RpcError-002: Error: {"result":null,"error":{"code":-5,"message":"No such mempool or blockchain transaction. Use gettransaction for wallet transactions."},"id":""}
  btcexp:error , json: {"code":500,"userData":{"request":{"method":"getrawtransaction","parameters":["<some unknown txid>",1]}}}, userData: [object Object] (json: {"request":"getrawtransaction([\"<some unknown txid>\",1])"}) +4m
  btcexp:errorVerbose Stack: Error: {"result":null,"error":{"code":-5,"message":"No such mempool or blockchain transaction. Use gettransaction for wallet transactions."},"id":""}
  btcexp:errorVerbose
  btcexp:errorVerbose     at IncomingMessage.<anonymous> (/home/user/.nvm/versions/node/v18.19.1/lib/node_modules/btc-rpc-explorer/node_modules/jayson/lib/client/http.js:78:23)
  btcexp:errorVerbose     at IncomingMessage.emit (node:events:529:35)
  btcexp:errorVerbose     at endReadableNT (node:internal/streams/readable:1400:12)
  btcexp:errorVerbose     at process.processTicksAndRejections (node:internal/process/task_queues:82:21) +4m
  btcexp:error Error awaitPromises_rejected: Error: {"result":null,"error":{"code":-5,"message":"No such mempool or blockchain transaction. Use gettransaction for wallet transactions."},"id":""}
  btcexp:error , json: {"code":500,"userData":{"request":{"method":"getrawtransaction","parameters":["<some unknown txid>",1]}}}, userData: [object Object] (json: {}) +4ms
  btcexp:errorVerbose Stack: Error: {"result":null,"error":{"code":-5,"message":"No such mempool or blockchain transaction. Use gettransaction for wallet transactions."},"id":""}
  btcexp:errorVerbose
  btcexp:errorVerbose     at IncomingMessage.<anonymous> (/home/user/.nvm/versions/node/v18.19.1/lib/node_modules/btc-rpc-explorer/node_modules/jayson/lib/client/http.js:78:23)
  btcexp:errorVerbose     at IncomingMessage.emit (node:events:529:35)
  btcexp:errorVerbose     at endReadableNT (node:internal/streams/readable:1400:12)
  btcexp:errorVerbose     at process.processTicksAndRejections (node:internal/process/task_queues:82:21) +2ms
  express:router <anonymous>  : /block-height/836999 +193ms
  express:router <anonymous>  : /block-height/836999 +0ms
  express:router <anonymous>  : /block-height/836999 +0ms
  **btcexp:error Error ExpressUncaughtError: ReferenceError: blockHeight is not defined, json: {}, userData: [object Object] (json: {}) +8ms**
  btcexp:errorVerbose Stack: ReferenceError: blockHeight is not defined
  btcexp:errorVerbose     at /home/user/.nvm/versions/node/v18.19.1/lib/node_modules/btc-rpc-explorer/routes/baseRouter.js:1116:70
  btcexp:errorVerbose     at process.processTicksAndRejections (node:internal/process/task_queues:95:5) +8ms
  express:view render "/home/user/.nvm/versions/node/v18.19.1/lib/node_modules/btc-rpc-explorer/views/error.pug" +2ms
  compression gzip compression +1m
  express-session touching +205ms
  memorystore EXPIRE "session-1ub-NRinOcz" ttl:86400000 +207ms
  express-session touched +3ms
  express:router dispatching GET /snippet/quote/random +237ms
  express:router query  : /snippet/quote/random +0ms
  express:router expressInit  : /snippet/quote/random +0ms
  express:router middleware  : /snippet/quote/random +0ms
  express:router cookieParser  : /snippet/quote/random +0ms
  express:router jsonParser  : /snippet/quote/random +0ms
  body-parser:json skip empty body +434ms
  express:router urlencodedParser  : /snippet/quote/random +0ms
  body-parser:urlencoded skip empty body +0ms
  express:router session  : /snippet/quote/random +0ms
  express-session fetching session-1ub-NRinOcz +226ms
  memorystore GET "session-1ub-NRinOcz" +227ms
  memorystore GOT {"cookie":{"originalMaxAge":null,"expires":null,"secure":false,"httpOnly":true,"path":"/"},"host":"127.0.0.1","port":8332,"username":"__cookie__","userSettings":{"displayCurrency":"btc","localCurrency":"usd","uiTimezone":"local","uiTheme":"dark"},"csrfSecret":"-XGuDe","query":null} +0ms
  express-session session found +0ms
  express:router compression  : /snippet/quote/random +1ms
  express:router serveStatic  : /snippet/quote/random +0ms
  send stat "/home/user/.nvm/versions/node/v18.19.1/lib/node_modules/btc-rpc-explorer/public/snippet/quote/random" +433ms
  express:router <anonymous>  : /snippet/quote/random +0ms
  express:router <anonymous>  : /snippet/quote/random +0ms
  express:router csrf  : /snippet/quote/random +1ms
  express:router <anonymous>  : /snippet/quote/random +0ms
  express:router router  : /snippet/quote/random +0ms
  express:router dispatching GET /snippet/quote/random +0ms
  express:router trim prefix (/snippet) from url /snippet/quote/random +0ms
  express:router router /snippet : /snippet/quote/random +0ms
  express:router dispatching GET /quote/random +0ms
  express:view render "/home/user/.nvm/versions/node/v18.19.1/lib/node_modules/btc-rpc-explorer/views/snippets/quote.pug" +0ms
  compression gzip compression +236ms
  express:router <anonymous>  : /snippet/quote/random +1ms
  btcexp:access Finished action '/snippet/quote/random' (200) in 2ms
  express-session touching +3ms
  memorystore EXPIRE "session-1ub-NRinOcz" ttl:86400000 +3ms
  express-session touched +0ms
  btcexp:core Pruned caches: 266 -> 266 +1m

```

**Additional context**

I deleted the `<some unknown txid>` from the log. The log is from when trying to load missing block page, I don't know what this txid.

**Comment by sha-265** [comment]
I have `txindex=1` set. The problem still exists.
