### ISSUE TITLE
Latest commit gives error when clicking on any block to get info

### ISSUE THREAD

**Issue by tadeubas** [janoside/btc-rpc-explorer#664]
**Describe the bug**

When trying to click on a block I got an error

**Environment (please complete the following information):**

 - Bitcoin Core / Node Version [e.g. 0.16.3] v27.1.0
 - NodeJS Version [e.g. 9.x] v18.19.1
 - Browser [e.g. chrome, safari] brave
 - Code Version / Commit [e.g. ab6cde8] ffd802288d87d747b170dc6f065f788d90032a9c
 - Installation Method [e.g. "npm" or "source code"] source code
 
**Configuration file content**

Please include the content from the following files. **BE SURE TO MODIFY YOUR CREDENTIALS BEFORE SUBMITTING!!!**
 - bitcoin.conf:
```
# [relay]
# Accept transaction replace-by-fee without requiring replaceability signaling.
mempoolfullrbf=1
# Relay non-P2SH multisig transactions.
permitbaremultisig=0

# [rpc]
# Accept command line and JSON-RPC commands.
# Needed for electrs
server=1
# Bind to given address to listen for JSON-RPC connections. This option is ignored unless -rpcallowip is also passed. Port is optional and overrides -rpcport. Use [host]:port notation for IPv6. This option can be specified multiple times. (default: 127.0.0.1 and ::1 i.e., localhost)
rpcbind=0.0.0.0
# Allow JSON-RPC connections from specified source. Valid for <ip> are a single IP (e.g. 1.2.3.4), a network/netmask (e.g. 1.2.3.4/255.255.255.0) or a network/CIDR (e.g. 1.2.3.4/24). This option can be specified multiple times.
rpcallowip=0.0.0.0/0

```

 - Your btc-rpc-explorer environment configuration (either `$WORKING_DIR/.env` or `~/.config/btc-rpc-explorer.env`)
```
BTCEXP_BITCOIND_COOKIE=/media/myuser/mydisk/Bitcoin/.cookie

BTCEXP_ADDRESS_API=electrum

BTCEXP_ELECTRUM_SERVERS=tcp://127.0.0.1:50001

BTCEXP_ELECTRUM_TXINDEX=true

BTCEXP_PRIVACY_MODE=true

```

**To Reproduce**

1. Go to http://127.0.0.1:3002/
2. Click on any block
3. See error

**Screenshots or Log Output**

```
TypeError: btc-rpc-explorer/views/includes/shared-mixins.pug:227
    225| 
    226| 							
  > 227| 							if (!coinbaseTx && Object.keys(txInputs).length < tx.vin.length)
    228| 								+infoBadge
    229| 									span(data-bs-toggle="tooltip", title="Data truncated by performance settings. See transaction details for fee info.")
    230| 										span.fw-light …

Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at Object.eval (eval at wrap (btc-rpc-explorer/node_modules/pug-runtime/wrap.js:6:10), <anonymous>:479:28)
    at Object.pug_interp [as txList] (eval at wrap (btc-rpc-explorer/node_modules/pug-runtime/wrap.js:6:10), <anonymous>:1102:4)
    at block (eval at wrap (btc-rpc-explorer/node_modules/pug-runtime/wrap.js:6:10), <anonymous>:5443:21)
    at Object.pug_interp (eval at wrap (btc-rpc-explorer/node_modules/pug-runtime/wrap.js:6:10), <anonymous>:173:10)
    at block (eval at wrap (btc-rpc-explorer/node_modules/pug-runtime/wrap.js:6:10), <anonymous>:5440:30)
    at Object.pug_interp (eval at wrap (btc-rpc-explorer/node_modules/pug-runtime/wrap.js:6:10), <anonymous>:1210:10)
    at eval (eval at wrap (btc-rpc-explorer/node_modules/pug-runtime/wrap.js:6:10), <anonymous>:4916:23)
    at template (eval at wrap (btc-rpc-explorer/node_modules/pug-runtime/wrap.js:6:10), <anonymous>:6019:7)
    at exports.renderFile (btc-rpc-explorer/node_modules/pug/lib/index.js:454:38)
```

**Comment by tadeubas** [comment]
Actually I can't see anything, tx and addr gives error 403: `ForbiddenError: invalid csrf token`, I've noticed this on logs:
```
btcexp:app txindex check: trying getindexinfo +0ms
btcexp:app txindex check: getindexinfo={} +3ms
btcexp:app txindex check: unavailable +0ms
```

**Comment by hasti0073** [comment]
1JjXPKN1yyPMxi2WvJv4BHVaJqqgzxSRGg

**Comment by tadeubas** [comment]
I've managed to access blocks by commenting the whole if: `if (!coinbaseTx && Object.keys(txInputs).length < tx.vin.length)`
