### ISSUE TITLE
Problem with zeromq when installinw with node.js 22.12.0

### ISSUE THREAD

**Issue by PabloQuiros** [janoside/btc-rpc-explorer#701]
Hi, I am getting this error when executing npm install:

npm error code 1
npm error path /home/pablo/btc-rpc-explorer/node_modules/zeromq
npm error command failed
npm error command sh -c node ./script/install.js
npm error Building addon node via cmake-ts (requires cmake, ninja, and the vcpkg dependencies)
npm error --------------------------------------------------
npm error       WARNING: Building only for the current runtime.
npm error       WARNING: DO NOT SHIP THE RESULTING PACKAGE
npm error      --------------------------------------------------
npm error no generator specified, checking ninja
npm error found ninja at /usr/bin/ninja
npm error running in /home/pablo/btc-rpc-explorer/node_modules/zeromq command [ 'nativeonly' ]
npm error > Setting up staging directory... [ DONE ]
npm error ---------------- BEGIN CONFIG ----------------
npm error > Distribution File Download... [ DONE ]
npm error > Determining ABI... [ DONE ]
npm error > Building directories... [ DONE ]
npm error > Applying overrides... [ DONE, 0 applied ]
npm error --------------- CONFIG SUMMARY ---------------
npm error Name:  N/A
npm error OS/Arch: linux arm64
npm error Runtime: node 22.12.0
npm error Target ABI: 127
npm error Toolchain File: null
npm error Custom CMake options: no
npm error Staging area: /home/pablo/btc-rpc-explorer/node_modules/zeromq/staging/linux/arm64/node/127
npm error Target directory: /home/pablo/btc-rpc-explorer/node_modules/zeromq/build/linux/arm64/node/127

I attach the rest of the log in the file
[npmErrorZeromq.txt](https://github.com/user-attachments/files/18132573/npmErrorZeromq.txt)

 - NodeJS Version 22.20
 - Code Version / Commit v.3.40
 - Installation Method: both npm and source code failed
 - 
I am working with a Raspberry Pi 5, with Raspbian

**Comment by PabloQuiros** [comment]
I have already fixed it with this command:
export VCPKG_FORCE_SYSTEM_BINARIES=1

**Comment by mntbighker** [comment]
Same issue here on Rocky9 I think (VCPKG didn't help me)...

```
npm error /home/btcrpcexplorer/.cache/node-gyp/23.5.0/include/node/v8-local-handle.h:267:42: note: ‘std::integral_constant<bool, false>::value’ evaluates to false
npm error make: *** [zmq.target.mk:115: Release/obj.target/zmq/binding.o] Error 1
npm error gyp ERR! build error
npm error gyp ERR! stack Error: `make` failed with exit code: 2
npm error gyp ERR! stack at ChildProcess.<anonymous> (/home/btcrpcexplorer/.nvm/versions/node/v23.6.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:216:23)
npm error gyp ERR! System Linux 5.14.0-503.19.1.el9_5.x86_64
npm error gyp ERR! command "/home/btcrpcexplorer/node_modules/node/bin/node" "/home/btcrpcexplorer/.nvm/versions/node/v23.6.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
npm error gyp ERR! cwd /home/btcrpcexplorer/btc-rpc-explorer/node_modules/zeromq
npm error gyp ERR! node -v v23.5.0
npm error gyp ERR! node-gyp -v v11.0.0
npm error gyp ERR! not ok
npm error A complete log of this run can be found in: /home/btcrpcexplorer/.npm/_logs/2025-01-08T04_03_18_191Z-debug-0.log

```

**Comment by lustremedia** [comment]
I am trying to install on arm64 Pi 5 and running into similar compiler issues ... using node 20.18.1

I have tried it with export VCPKG_FORCE_SYSTEM_BINARIES=1 but it did not work.

npm install
npm warn deprecated inflight@1.0.6: This module is not supported, and leaks memory. Do not use it. Check out lru-cache if you want a good and tested way to coalesce async requests by a key value, which is much more comprehensive and powerful.
npm warn deprecated npmlog@6.0.2: This package is no longer supported.
npm warn deprecated @humanwhocodes/config-array@0.13.0: Use @eslint/config-array instead
npm warn deprecated rimraf@3.0.2: Rimraf versions prior to v4 are no longer supported
npm warn deprecated are-we-there-yet@3.0.1: This package is no longer supported.
npm warn deprecated glob@7.2.3: Glob versions prior to v9 are no longer supported
npm warn deprecated @humanwhocodes/object-schema@2.0.3: Use @eslint/object-schema instead
npm warn deprecated gauge@4.0.4: This package is no longer supported.
npm warn deprecated eslint@8.57.1: This version is no longer supported. Please see https://eslint.org/version-support for other options.
npm error code 1
npm error path /home/btcrpcexplorer/btc-rpc-explorer/node_modules/zeromq
npm error command failed
npm error command sh -c node ./script/install.js
npm error Building addon node via cmake-ts (requires cmake, ninja, and the vcpkg dependencies)
npm error --------------------------------------------------
npm error       WARNING: Building only for the current runtime.
npm error       WARNING: DO NOT SHIP THE RESULTING PACKAGE
npm error      --------------------------------------------------
npm error no generator specified, checking ninja
npm error found ninja at /usr/bin/ninja
npm error running in /home/btcrpcexplorer/btc-rpc-explorer/node_modules/zeromq command [ 'nativeonly' ]
npm error > Setting up staging directory... [ DONE ]
npm error ---------------- BEGIN CONFIG ----------------
npm error > Distribution File Download... [ DONE ]
npm error > Determining ABI... [ DONE ]
npm error > Building directories... [ DONE ]
npm error > Applying overrides... [ DONE, 0 applied ]
npm error --------------- CONFIG SUMMARY ---------------
npm error Name:  N/A
npm error OS/Arch: linux arm64
npm error Runtime: node 20.18.1
npm error Target ABI: 115
npm error Toolchain File: null
npm error Custom CMake options: no


At the end it fails with this:

npm error [219/220] Building CXX object CMakeFiles/vcpkg-test.dir/src/vcpkg-test/versionplan.cpp.o
npm error [220/220] Linking CXX executable vcpkg-test
npm error vcpkg package management program version 2999-12-31-unknownhash
npm error
npm error See LICENSE.txt for license information.
npm error -- Running vcpkg install
npm error error: try_read_contents("/home/btcrpcexplorer/vcpkg/scripts/vcpkg-tools.json"): No such file or directory
npm error -- Running vcpkg install - failed
npm error -- Configuring incomplete, errors occurred!
npm error Generic error occured Error: Process terminated: 1
npm error     at ChildProcess.<anonymous> (/home/btcrpcexplorer/btc-rpc-explorer/node_modules/@aminya/cmake-ts/build/util.js:100:24)
npm error     at ChildProcess.emit (node:events:518:28)
npm error     at ChildProcess._handle.onexit (node:internal/child_process:293:12)
npm error Error: Failed to load zeromq.js addon.node: Error: ENOENT: no such file or directory, scandir '/home/btcrpcexplorer/btc-rpc-explorer/node_modules/zeromq/build/linux/arm64/node'
npm error Error: ENOENT: no such file or directory, scandir '/home/btcrpcexplorer/btc-rpc-explorer/node_modules/zeromq/build/linux/arm64/node'
npm error     at Object.readdirSync (node:fs:1506:26)
npm error     at findAddon (/home/btcrpcexplorer/btc-rpc-explorer/node_modules/zeromq/lib/load-addon.js:22:43)
npm error     at Object.<anonymous> (/home/btcrpcexplorer/btc-rpc-explorer/node_modules/zeromq/lib/load-addon.js:50:15)
npm error     at Module._compile (node:internal/modules/cjs/loader:1469:14)
npm error     at Module._extensions..js (node:internal/modules/cjs/loader:1548:10)
npm error     at Module.load (node:internal/modules/cjs/loader:1288:32)
npm error     at Module._load (node:internal/modules/cjs/loader:1104:12)
npm error     at Module.require (node:internal/modules/cjs/loader:1311:19)
npm error     at require (node:internal/modules/helpers:179:18)
npm error     at main (/home/btcrpcexplorer/btc-rpc-explorer/node_modules/zeromq/script/install.js:26:7)
npm error     at findAddon (/home/btcrpcexplorer/btc-rpc-explorer/node_modules/zeromq/lib/load-addon.js:43:15)
npm error     at Object.<anonymous> (/home/btcrpcexplorer/btc-rpc-explorer/node_modules/zeromq/lib/load-addon.js:50:15)
npm error     at Module._compile (node:internal/modules/cjs/loader:1469:14)
npm error     at Module._extensions..js (node:internal/modules/cjs/loader:1548:10)
npm error     at Module.load (node:internal/modules/cjs/loader:1288:32)
npm error     at Module._load (node:internal/modules/cjs/loader:1104:12)
npm error     at Module.require (node:internal/modules/cjs/loader:1311:19)
npm error     at require (node:internal/modules/helpers:179:18)
npm error     at main (/home/btcrpcexplorer/btc-rpc-explorer/node_modules/zeromq/script/install.js:26:7)
npm error     at Object.<anonymous> (/home/btcrpcexplorer/btc-rpc-explorer/node_modules/zeromq/script/install.js:34:1)
npm error 'os' was missing in the 'configurations'. Defaulting to the current operating system linux
npm error 'arch' was missing in the 'configurations'. Defaulting to the current architecture arm64
npm error `runtime` was missing in the `configurations`. Defaulting to `node`
npm error 'runtimeVersion' was missing in the 'configurations'. Defaulting to the current runtimeVersion 20.18.1
npm error Cloning into '/home/btcrpcexplorer/vcpkg'...
npm error HEAD is now at ee2d2a100 [netcpp] Update to 0.5.0 (#40870)
npm error CMake Error at /home/btcrpcexplorer/vcpkg/scripts/buildsystems/vcpkg.cmake:904 (message):
npm error   vcpkg install failed.  See logs for more information:
npm error   /home/btcrpcexplorer/btc-rpc-explorer/node_modules/zeromq/staging/linux/arm64/node/115/vcpkg-manifest-install.log
npm error Call Stack (most recent call first):
npm error   /usr/share/cmake-3.25/Modules/CMakeDetermineSystem.cmake:124 (include)
npm error   CMakeLists.txt:104 (project)
npm error
npm error
npm error CMake Error: CMake was unable to find a build program corresponding to "Ninja".  CMAKE_MAKE_PROGRAM is not set.  You probably need to select a different build tool.
npm error CMake Error: CMAKE_C_COMPILER not set, after EnableLanguage
npm error CMake Error: CMAKE_CXX_COMPILER not set, after EnableLanguage
npm error node:child_process:930
npm error     throw err;
npm error     ^
npm error
npm error Error: Command failed: /usr/bin/node /home/btcrpcexplorer/btc-rpc-explorer/node_modules/@aminya/cmake-ts/build/main.js nativeonly
npm error     at genericNodeError (node:internal/errors:984:15)
npm error     at wrappedFn (node:internal/errors:538:14)
npm error     at checkExecSyncError (node:child_process:891:11)
npm error     at Object.execFileSync (node:child_process:927:15)
npm error     at cmakeTs (/home/btcrpcexplorer/btc-rpc-explorer/node_modules/zeromq/script/install.js:10:6)
npm error     at main (/home/btcrpcexplorer/btc-rpc-explorer/node_modules/zeromq/script/install.js:29:7)
npm error     at Object.<anonymous> (/home/btcrpcexplorer/btc-rpc-explorer/node_modules/zeromq/script/install.js:34:1)
npm error     at Module._compile (node:internal/modules/cjs/loader:1469:14)
npm error     at Module._extensions..js (node:internal/modules/cjs/loader:1548:10)
npm error     at Module.load (node:internal/modules/cjs/loader:1288:32) {
npm error   status: 1,
npm error   signal: null,
npm error   output: [ null, null, null ],
npm error   pid: 22502,
npm error   stdout: null,
npm error   stderr: null
npm error }
npm error
npm error Node.js v20.18.1

**Comment by cheinig** [comment]
Upgrading the zeromq version in the package.json file from 5.3.1 to current 6.3.0 worked for me. Maybe someone can test this out.

**Comment by twofaktor** [comment]
> Upgrading the zeromq version in the package.json file from 5.3.1 to current 6.3.0 worked for me. Maybe someone can test this out.

Oh yeah, it worked for me! Thanks! PR opened https://github.com/janoside/btc-rpc-explorer/pull/727

**Comment by twofaktor** [comment]
This PR should be closed, solved here https://github.com/janoside/btc-rpc-explorer/commit/26e282a06e87b645c6e0687e2503d26d1e623dea
