### ISSUE TITLE
bug when entering TX id in search bar

### ISSUE THREAD

**Issue by Zhell1** [janoside/btc-rpc-explorer#74]
```
Error
/home/ubuntu/site/btc-rpc-explorer/views/transaction.pug:106 104| div(class="row") 105| div(class="summary-table-label") Virtual Size > 106| div(class="summary-table-content monospace") #{result.getrawtransaction.vsize.toLocaleString()} VB 107| 108| div(class="row") 109| div(class="summary-table-label") Size Cannot read property 'toLocaleString' of undefined

TypeError: /home/ubuntu/site/btc-rpc-explorer/views/transaction.pug:106
    104| 							div(class="row")
    105| 								div(class="summary-table-label") Virtual Size
  > 106| 								div(class="summary-table-content monospace") #{result.getrawtransaction.vsize.toLocaleString()} VB
    107| 
    108| 						div(class="row")
    109| 							div(class="summary-table-label") Size

Cannot read property 'toLocaleString' of undefined
    at eval (eval at wrap (/home/ubuntu/site/btc-rpc-explorer/node_modules/pug-runtime/wrap.js:6:10), <anonymous>:698:88)
    at template (eval at wrap (/home/ubuntu/site/btc-rpc-explorer/node_modules/pug-runtime/wrap.js:6:10), <anonymous>:2297:72)
    at Object.exports.renderFile (/home/ubuntu/site/btc-rpc-explorer/node_modules/pug/lib/index.js:427:38)
    at Object.exports.renderFile (/home/ubuntu/site/btc-rpc-explorer/node_modules/pug/lib/index.js:417:21)
    at exports.__express (/home/ubuntu/site/btc-rpc-explorer/node_modules/pug/lib/index.js:464:11)
    at View.app.engine (/home/ubuntu/site/btc-rpc-explorer/app.js:40:23)
    at View.render (/home/ubuntu/site/btc-rpc-explorer/node_modules/express/lib/view.js:135:8)
    at tryRender (/home/ubuntu/site/btc-rpc-explorer/node_modules/express/lib/application.js:640:10)
    at Function.render (/home/ubuntu/site/btc-rpc-explorer/node_modules/express/lib/application.js:592:3)
    at ServerResponse.render (/home/ubuntu/site/btc-rpc-explorer/node_modules/express/lib/response.js:1008:7)
    at /home/ubuntu/site/btc-rpc-explorer/routes/baseActionsRouter.js:498:9
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

**Comment by janoside** [comment]
@Zhell1 What version is your bitcoin node software?
