### ISSUE TITLE
.length of undefines. please help

### ISSUE THREAD

**Issue by SIKOo971** [janoside/btc-rpc-explorer#79]
today i installed btc-rpc-explorer by given instruction, but whenever i try to **run npm** start and go to **172.0.0.1:3002**. its given me error 

Running RPC Explorer for Bitcoin
Connecting via RPC to node at 127.0.0.1:8332
Connecting to ElectrumX Server: E-X.not.fyi:50002
Using exchange rate: 3673.42145167 USD/Bitcoin starting at Thu Dec 06 2018 15:36:58 GMT-0500 (Eastern Standard Time)
Connected to ElectrumX Server: E-X.not.fyi:50002, versions: [object Object]
Live with ElectrumX API.
rpc.getBlocksByHash: 00000000000000000000d16fa701f48b56d26ad4be9250a61d15e2dd8c07f066,0000000000000000001d2fad47f0fb12e0642e7b733e13e062218bea85dded41,0000000000000000001994fb7752bbf4effd1eaed4e7a758cb1c8105e54160b8,0000000000000000001996131122c2c86fa82a30b184488b41ae0d4ce67f3f2d,0000000000000000000d7a352acb0f615ed9722bc401c7c4167fefddb0664b50,0000000000000000000b2062ed3480175a86d02544da595c0d69d925098f7940,0000000000000000001f957169b71705f353888322362fdc1da5d83f0386e96b,0000000000000000000e9eaaed3635b980bd449496a77513ec589c3c1254ee3b,00000000000000000016c460f4edfa572fcc34a5e445522aa27b646d3be57429,00000000000000000024c82694fadf93945b2a64b7228ea24cd8d11c87b8c2e6
Starting 1-item batch Tgb5QloBF5qPP8RJAcHd...
Executing item #1 (of 1) for batch Tgb5QloBF5qPP8RJAcHd
Finishing batch Tgb5QloBF5qPP8RJAcHd...
**Unhandled Rejection at: Promise Promise {
  <rejected> TypeError: Cannot read property 'length' of undefined
      at Object.getBlockTotalFeesFromCoinbaseTxAndBlockHeight (/home/abc/btc-rpc-explorer/app/utils.js:260:38)
      at /home/abc/btc-rpc-explorer/app/api/rpcApi.js:127:34
      at process._tickCallback (internal/process/next_tick.js:68:7) } reason: TypeError: Cannot read property 'length' of undefined
    at Object.getBlockTotalFeesFromCoinbaseTxAndBlockHeight (/home/abc/btc-rpc-explorer/app/utils.js:260:38)
    at /home/abc/btc-rpc-explorer/app/api/rpcApi.js:127:34
    at process._tickCallback (internal/process/next_tick.js:68:7) stack: TypeError: Cannot read property 'length' of undefined
    at Object.getBlockTotalFeesFromCoinbaseTxAndBlockHeight (/home/abc/btc-rpc-explorer/app/utils.js:260:38)
    at /home/abc/btc-rpc-explorer/app/api/rpcApi.js:127:34
    at process._tickCallback (internal/process/next_tick.js:68:7)**

**Comment by Moller40** [comment]
Get the same error. Any workaround found?

**Comment by Moller40** [comment]
It happens if changing to txindex=1 of an existing node and the "Syncing txindex" not is done (check the Bitcoin Core debug log file). Problem went away when the syncing was done.
